feat(comment): open urls in the comment in a new tab
DigiThinkIT/frappe pull request #113
Opened 2019-07-26 10:59 UTC by DeeMysterio

**Task:** [TASK-2019-00378](https://digithinkit.global/desk#Form/Task/TASK-2019-00378)

2019-07-26 11:05 UTC, DeeMysterio commented
@forellana-digithinkit Is there a better way to do this?

2019-07-29 12:56 UTC, DeveloperMetal requested changes

2019-07-29 12:56 UTC, forellana-digithinkit commented on frappe/public/js/frappe/misc/utils.js
> +		return html.replace("href", " target='_blank' href");
I don't feel this is a good solution for this issue. What if the element already had an target attribute? 
now you've added two and if the target attribute comes after the one you just injected your target attribute might get ignored by the browser.

Instead use the BeautifulSoup module already included in frappe to do this predictably.

https://www.crummy.com/software/BeautifulSoup/bs4/doc/

2019-08-05 14:46 UTC, forellana-digithinkit commented on frappe/public/js/frappe/misc/utils.js
> +		return new XMLSerializer().serializeToString(doc);
As per your question I believe you could just use the innerHTML property of your doc to have it serialize for you:

```js
return doc.documentElement.innerHTML;
```

2019-08-06 16:07 UTC, Alchez commented on frappe/public/js/frappe/misc/utils.js
> +				anchors.forEach(anchor => {anchor.target = "_blank";});
Should the target be a passed argument instead? @forellana-digithinkit

2019-08-09 04:49 UTC, forellana-digithinkit commented on frappe/public/js/frappe/misc/utils.js
> +				anchors.forEach(anchor => {anchor.target = "_blank";});
@Alchez Do you mean in the utility function, in case you don't want _blank and maybe override with with something else?

If so, that's a possibility but I wouldn't add it until necessary. Keep code base small, less potential bugs to worry about.

2019-08-09 12:02 UTC, Alchez commented on frappe/public/js/frappe/misc/utils.js
> +				anchors.forEach(anchor => {anchor.target = "_blank";});
Alright, makes sense

2019-08-09 12:09 UTC, DeveloperMetal approved these changes
If things are tested I'm Ok(ish) with this

2019-08-09 12:10 UTC, merged

2019-08-12 12:29 UTC, dti-deploy commented
:tada: This PR is included in version 1.2.0 :tada:

The release is available on [GitHub release](https://github.com/DigiThinkIT/frappe/releases/tag/v1.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: