check if the buttom exists or not before adding it
DigiThinkIT/frappe pull request #13
Opened 2018-05-08 05:21 UTC by sushantnadkar

2018-05-11 14:40 UTC, DeveloperMetal requested changes

2018-05-11 14:40 UTC, forellana-digithinkit commented on frappe/public/js/frappe/ui/page.js
> +			if( button.length == 0 ) {
change that to ===

2018-05-11 14:40 UTC, forellana-digithinkit commented on frappe/public/js/frappe/ui/page.js
> +			}
So, here is what I'm worried about this code... If a button already exists, this will run ALL setup behavior up to this point to build a button. But never return a button if one already exists. 

Are we leaving the toolbar is a bad state here?

Do you know what the receiving end of this return looks like and if it doesn't get an expected jquery element it won't cause further issues in the future?

If you can point me at where this return value usually gets handled I could take a look for you and make sure we are not just creating more bugs(hopefully)

2018-05-14 04:53 UTC, sushantnadkar commented on frappe/public/js/frappe/ui/page.js
> +			}
I am not sure but this shouldn't cause an issue, because if we are adding another drop-down option it doesn't return anything, but still, I found an instance where a call to `add_custom_button` (form.js - line 918) which in turn calls `add_inner_button`, expects a return value (warrenty_request.js - line 309).

2018-05-15 16:02 UTC, forellana-digithinkit commented
Ok, so here is a potential bug...

on: https://github.com/DigiThinkIT/frappe/blob/customv10/frappe/public/js/legacy/form.js#L918-L924

when we call add_inner_button, the code is expecting a button to return: https://github.com/DigiThinkIT/frappe/blob/customv10/frappe/public/js/legacy/form.js#L921

This is used to keep state of the buttons so they can be cleaned up later at: https://github.com/DigiThinkIT/frappe/blob/customv10/frappe/public/js/legacy/form.js#L927 

So if we return nothing we'll be unsetting any previous button that was stored there.
So, if we don't want to return anything edit and possibly break something down the chain(specially cleanup) check the return value at:

https://github.com/DigiThinkIT/frappe/blob/customv10/frappe/public/js/legacy/form.js#L927 

and don't set the custom_buttons[label] = btn if btn is null

2018-05-16 06:45 UTC, sushantnadkar commented
Not setting the `custom_buttons[label] = btn` if `btn` is `undefined`, is not enough as there are places where a return value is expected, for example, 
```
frm.add_custom_button(__("Button text"), function () {
    //some code
}).addClass("btn-primary");
```
in [warranty_management/doctype/warranty_request/warranty_request.js#L309](https://github.com/DigiThinkIT/jhaudio_warranty_management/blob/a467fe5b0663389a46a4ab6d2ca538aa59787f0a/warranty_management/warranty_management/doctype/warranty_request/warranty_request.js#L309)

So returned the `button` object if the button already exists along with not setting `custom_button[label] = btn`.

2018-05-16 13:49 UTC, DeveloperMetal approved these changes
Cool, good thinking in returning the found button.

2018-05-17 06:24 UTC, merged