feat: open task in new tab using anchor tag
DigiThinkIT/frappe pull request #168
Opened 2020-01-14 11:52 UTC by Er-Naren719

**Task link:** https://digithinkit.global/desk#Form/Task/TASK-2019-00325

**Description:** Open task in new link using anchor tag

**GIF:**
![open_task_in_new_tab](https://user-images.githubusercontent.com/49683121/71971087-e2e91800-322f-11ea-829a-cc1ba7128a14.gif)

2020-01-14 11:58 UTC, vjFaLk commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 336
- Added 587
           

Complexity increasing per file
==============================
- frappe/desk/page/leaderboard/leaderboard.js  3
- frappe/desk/link_preview.py  13
- frappe/database/db_manager.py  4
- frappe/automation/doctype/milestone_tracker/milestone_tracker.py  4
- frappe/core/doctype/server_script/test_server_script.py  2
- frappe/desk/doctype/onboarding_slide/onboarding_slide.js  3
- frappe/public/js/frappe/web_form/web_form_list.js  4
- frappe/public/js/frappe/ui/dialog.js  1
- frappe/desk/doctype/notification_settings/notification_settings.js  1
- frappe/integrations/doctype/ldap_settings/test_ldap_settings.py  1
- frappe/core/doctype/server_script/server_script_utils.py  6
- frappe/public/js/frappe/views/modules_home.js  1
- frappe/automation/doctype/auto_repeat/auto_repeat.js  3
- frappe/website/doctype/website_theme/website_theme.js  8
- frappe/core/doctype/session_default_settings/session_default_settings.js  1
- frappe/public/js/frappe/form/grid_pagination.js  3
- frappe/core/doctype/communication_link/communication_link.py  1
- frappe/contacts/doctype/contact/test_contact.py  5
- frappe/www/sitemap.py  2
- cypress/integration/table_multiselect.js  1
- frappe/desk/listview.py  2
- frappe/tests/test_pdf.py  1
- frappe/social/doctype/energy_point_settings/energy_point_settings.js  1
- frappe/core/doctype/permission_request/permission_request.py  3
- frappe/desk/doctype/onboarding_slide_help_link/onboarding_slide_help_link.py  1
- frappe/integrations/doctype/ldap_group_mapping/ldap_group_mapping.py  1
- frappe/public/js/frappe/file_uploader/index.js  5
- frappe/patches/v12_0/delete_feedback_request_if_exists.py  1
- frappe/core/doctype/translation/translation.py  2
- frappe/public/js/frappe/form/sidebar/user_image.js  7
- frappe/public/js/frappe/data_import/column_picker_fields.js  2
- frappe/core/doctype/session_default_settings/session_default_settings.py  4
- frappe/model/__init__.py  2
- frappe/public/js/frappe/web_form/webform_script.js  7
- frappe/social/doctype/energy_point_log/energy_point_log.js  4
- cypress/integration/control_rating.js  1
- frappe/core/doctype/permission_request/permission_request_list.js  1
- frappe/desk/doctype/global_search_settings/global_search_settings.py  14
- frappe/public/js/frappe/form/script_helpers.js  9
- cypress/integration/awesome_bar.js  1
- frappe/tests/test_db.py  1
- frappe/website/doctype/personal_data_deletion_request/personal_data_deletion_request.py  10
- frappe/core/doctype/access_log/access_log.js  3
- frappe/public/js/frappe/microtemplate.js  8
- frappe/public/js/frappe/form/sidebar/document_follow.js  6
- frappe/desk/doctype/onboarding_slide/test_onboarding_slide.py  1
- frappe/utils/formatters.py  3
- frappe/desk/doctype/dashboard_chart/test_dashboard_chart.py  3
- frappe/patches/v12_0/set_default_incoming_email_port.py  4
- frappe/public/js/frappe/ui/onboarding_dialog.js  4
- frappe/core/doctype/server_script/server_script.py  4
- frappe/public/js/frappe/form/controls/multiselect_list.js  5
- frappe/core/doctype/user_permission/user_permission.py  1
- frappe/public/js/frappe/list/base_list.js  2
- frappe/public/js/frappe/form/toolbar.js  2
- frappe/desk/moduleview.py  1
- frappe/public/js/lib/Sortable.min.js  1
- frappe/public/js/frappe/list/list_view.js  7
- frappe/core/doctype/file/file.py  4
- frappe/core/page/dashboard/dashboard.js  4
- frappe/core/doctype/data_import_beta/data_import_beta.js  10
- frappe/deferred_insert.py  6
- frappe/public/js/frappe/form/sidebar/form_sidebar.js  4
- frappe/social/doctype/energy_point_log/test_energy_point_log.py  2
- frappe/tests/test_email.py  1
- frappe/public/js/frappe/list/list_sidebar.js  1
- frappe/app.py  4
- frappe/patches/v12_0/setup_tags.py  9
- frappe/desk/reportview.py  2
- frappe/core/doctype/doctype/doctype.py  1
- frappe/tests/test_sitemap.py  1
- frappe/public/js/frappe/router_history.js  5
- frappe/social/doctype/energy_point_rule/energy_point_rule.py  12
- frappe/social/doctype/energy_point_log/energy_point_log_list.js  1
- frappe/core/doctype/docfield/docfield.py  4
- frappe/patches/v7_2/set_in_standard_filter_property.py  1
- frappe/public/js/frappe/social/social_factory.js  2
- frappe/desk/page/user_profile/user_profile.js  3
- frappe/tests/test_formatter.py  1
- frappe/email/doctype/document_follow/test_document_follow.py  1
- frappe/website/doctype/blog_post/blog_post.py  2
- cypress/support/commands.js  4
- frappe/patches/v11_0/drop_column_apply_user_permissions.py  1
- frappe/model/delete_doc.py  6
- frappe/database/schema.py  19
- frappe/public/js/frappe/list/list_sidebar_group_by.js  4
- cypress/integration/file_uploader.js  1
- frappe/social/doctype/post/post.js  1
- frappe/core/doctype/data_import/importer_new.py  34
- frappe/utils/safe_exec.py  12
- frappe/desk/doctype/list_view_setting/list_view_setting.py  1
- frappe/patches/v12_0/remove_deprecated_fields_from_doctype.py  1
- frappe/automation/doctype/assignment_rule/assignment_rule.py  22
- frappe/tests/test_listview.py  3
- frappe/social/doctype/energy_point_log/energy_point_log.py  10
- cypress/integration/recorder.js  1
- frappe/patches/v12_0/delete_gsuite_if_exists.py  1
- frappe/public/js/frappe/form/sidebar/attachments.js  4
- frappe/public/js/frappe/data_import/data_exporter.js  4
- frappe/core/doctype/communication/communication.py  1
- frappe/desk/doctype/tag_link/tag_link.py  1
- cypress/integration/relative_filters.js  1
- frappe/tests/ui_test_helpers.py  4
- frappe/core/doctype/doctype/doctype.js  3
- frappe/integrations/doctype/google_calendar/google_calendar.py  21
- frappe/core/doctype/session_default_settings/test_session_default_settings.py  1
- frappe/database/mariadb/setup_db.py  6
- frappe/social/doctype/post_comment/post_comment.py  3
- frappe/patches/v12_0/move_timeline_links_to_dynamic_links.py  10
- frappe/utils/oauth.py  3
- frappe/core/doctype/data_import_beta/data_import_beta.py  5
- frappe/core/doctype/version/version.py  1
- frappe/website/doctype/personal_data_deletion_request/test_personal_data_deletion_request.py  1
- frappe/public/js/frappe/web_form/web_form.js  8
- frappe/public/js/frappe/form/controls/table_multiselect.js  6
- frappe/desk/doctype/global_search_doctype/global_search_doctype.py  1
- frappe/desk/doctype/tag/test_tag.py  1
- frappe/public/js/frappe/form/controls/base_control.js  1
- frappe/config/settings.py  1
- frappe/website/doctype/personal_data_download_request/personal_data_download_request.py  3
- frappe/email/utils.py  5
- frappe/patches/v12_0/init_desk_settings.py  1
- frappe/core/doctype/scheduled_job_type/test_scheduled_job_type.py  2
- frappe/website/js/bootstrap-4.js  2
- frappe/public/js/frappe/utils/help.js  4
- frappe/core/doctype/doctype_link/doctype_link.py  1
- frappe/core/doctype/comment/comment.py  11
- frappe/public/js/frappe/utils/number_format.js  18
- frappe/core/doctype/data_import/test_exporter_new.py  1
- frappe/desk/doctype/notification_log/notification_log.js  1
- frappe/website/web_form/request_to_delete_data/request_to_delete_data.py  1
- frappe/patches/v12_0/create_notification_settings_for_user.py  2
- frappe/integrations/doctype/webhook/test_webhook.py  1
- frappe/public/js/frappe/form/controls/markdown_editor.js  3
- frappe/public/js/frappe/utils/address_and_contact.js  5
- frappe/core/doctype/data_import/exporter_new.py  11
- frappe/public/js/frappe/ui/toolbar/tag_utils.js  3
- frappe/utils/html_utils.py  1
- frappe/core/doctype/scheduled_job_log/test_scheduled_job_log.py  1
- frappe/desk/doctype/dashboard/dashboard.py  2
- frappe/website/doctype/blog_post/test_blog_post.py  2
- frappe/public/js/frappe/form/sidebar/form_viewers.js  9
- frappe/core/doctype/access_log/test_access_log.py  3
- frappe/core/doctype/report/report.js  1
- frappe/desk/form/document_follow.py  8
- frappe/patches/v12_0/reset_home_settings.p [...]

2020-01-14 12:02 UTC, Er-Naren719 commented
> ![Codacy](https://camo.githubusercontent.com/b72992711a855bd9a03bfbdfc5ef7fcf528482f5/68747470733a2f2f6170702e636f646163792e636f6d2f6173736574732f696d616765732f66617669636f6e2e706e67) Here is an overview of what got changed by this pull request:
> 
> ```diff
> Issues
> ======
> + Solved 336
> - Added 587
>            
> 
> Complexity increasing per file
> ==============================
> - frappe/desk/page/leaderboard/leaderboard.js  3
> - frappe/desk/link_preview.py  13
> - frappe/database/db_manager.py  4
> - frappe/automation/doctype/milestone_tracker/milestone_tracker.py  4
> - frappe/core/doctype/server_script/test_server_script.py  2
> - frappe/desk/doctype/onboarding_slide/onboarding_slide.js  3
> - frappe/public/js/frappe/web_form/web_form_list.js  4
> - frappe/public/js/frappe/ui/dialog.js  1
> - frappe/desk/doctype/notification_settings/notification_settings.js  1
> - frappe/integrations/doctype/ldap_settings/test_ldap_settings.py  1
> - frappe/core/doctype/server_script/server_script_utils.py  6
> - frappe/public/js/frappe/views/modules_home.js  1
> - frappe/automation/doctype/auto_repeat/auto_repeat.js  3
> - frappe/website/doctype/website_theme/website_theme.js  8
> - frappe/core/doctype/session_default_settings/session_default_settings.js  1
> - frappe/public/js/frappe/form/grid_pagination.js  3
> - frappe/core/doctype/communication_link/communication_link.py  1
> - frappe/contacts/doctype/contact/test_contact.py  5
> - frappe/www/sitemap.py  2
> - cypress/integration/table_multiselect.js  1
> - frappe/desk/listview.py  2
> - frappe/tests/test_pdf.py  1
> - frappe/social/doctype/energy_point_settings/energy_point_settings.js  1
> - frappe/core/doctype/permission_request/permission_request.py  3
> - frappe/desk/doctype/onboarding_slide_help_link/onboarding_slide_help_link.py  1
> - frappe/integrations/doctype/ldap_group_mapping/ldap_group_mapping.py  1
> - frappe/public/js/frappe/file_uploader/index.js  5
> - frappe/patches/v12_0/delete_feedback_request_if_exists.py  1
> - frappe/core/doctype/translation/translation.py  2
> - frappe/public/js/frappe/form/sidebar/user_image.js  7
> - frappe/public/js/frappe/data_import/column_picker_fields.js  2
> - frappe/core/doctype/session_default_settings/session_default_settings.py  4
> - frappe/model/__init__.py  2
> - frappe/public/js/frappe/web_form/webform_script.js  7
> - frappe/social/doctype/energy_point_log/energy_point_log.js  4
> - cypress/integration/control_rating.js  1
> - frappe/core/doctype/permission_request/permission_request_list.js  1
> - frappe/desk/doctype/global_search_settings/global_search_settings.py  14
> - frappe/public/js/frappe/form/script_helpers.js  9
> - cypress/integration/awesome_bar.js  1
> - frappe/tests/test_db.py  1
> - frappe/website/doctype/personal_data_deletion_request/personal_data_deletion_request.py  10
> - frappe/core/doctype/access_log/access_log.js  3
> - frappe/public/js/frappe/microtemplate.js  8
> - frappe/public/js/frappe/form/sidebar/document_follow.js  6
> - frappe/desk/doctype/onboarding_slide/test_onboarding_slide.py  1
> - frappe/utils/formatters.py  3
> - frappe/desk/doctype/dashboard_chart/test_dashboard_chart.py  3
> - frappe/patches/v12_0/set_default_incoming_email_port.py  4
> - frappe/public/js/frappe/ui/onboarding_dialog.js  4
> - frappe/core/doctype/server_script/server_script.py  4
> - frappe/public/js/frappe/form/controls/multiselect_list.js  5
> - frappe/core/doctype/user_permission/user_permission.py  1
> - frappe/public/js/frappe/list/base_list.js  2
> - frappe/public/js/frappe/form/toolbar.js  2
> - frappe/desk/moduleview.py  1
> - frappe/public/js/lib/Sortable.min.js  1
> - frappe/public/js/frappe/list/list_view.js  7
> - frappe/core/doctype/file/file.py  4
> - frappe/core/page/dashboard/dashboard.js  4
> - frappe/core/doctype/data_import_beta/data_import_beta.js  10
> - frappe/deferred_insert.py  6
> - frappe/public/js/frappe/form/sidebar/form_sidebar.js  4
> - frappe/social/doctype/energy_point_log/test_energy_point_log.py  2
> - frappe/tests/test_email.py  1
> - frappe/public/js/frappe/list/list_sidebar.js  1
> - frappe/app.py  4
> - frappe/patches/v12_0/setup_tags.py  9
> - frappe/desk/reportview.py  2
> - frappe/core/doctype/doctype/doctype.py  1
> - frappe/tests/test_sitemap.py  1
> - frappe/public/js/frappe/router_history.js  5
> - frappe/social/doctype/energy_point_rule/energy_point_rule.py  12
> - frappe/social/doctype/energy_point_log/energy_point_log_list.js  1
> - frappe/core/doctype/docfield/docfield.py  4
> - frappe/patches/v7_2/set_in_standard_filter_property.py  1
> - frappe/public/js/frappe/social/social_factory.js  2
> - frappe/desk/page/user_profile/user_profile.js  3
> - frappe/tests/test_formatter.py  1
> - frappe/email/doctype/document_follow/test_document_follow.py  1
> - frappe/website/doctype/blog_post/blog_post.py  2
> - cypress/support/commands.js  4
> - frappe/patches/v11_0/drop_column_apply_user_permissions.py  1
> - frappe/model/delete_doc.py  6
> - frappe/database/schema.py  19
> - frappe/public/js/frappe/list/list_sidebar_group_by.js  4
> - cypress/integration/file_uploader.js  1
> - frappe/social/doctype/post/post.js  1
> - frappe/core/doctype/data_import/importer_new.py  34
> - frappe/utils/safe_exec.py  12
> - frappe/desk/doctype/list_view_setting/list_view_setting.py  1
> - frappe/patches/v12_0/remove_deprecated_fields_from_doctype.py  1
> - frappe/automation/doctype/assignment_rule/assignment_rule.py  22
> - frappe/tests/test_listview.py  3
> - frappe/social/doctype/energy_point_log/energy_point_log.py  10
> - cypress/integration/recorder.js  1
> - frappe/patches/v12_0/delete_gsuite_if_exists.py  1
> - frappe/public/js/frappe/form/sidebar/attachments.js  4
> - frappe/public/js/frappe/data_import/data_exporter.js  4
> - frappe/core/doctype/communication/communication.py  1
> - frappe/desk/doctype/tag_link/tag_link.py  1
> - cypress/integration/relative_filters.js  1
> - frappe/tests/ui_test_helpers.py  4
> - frappe/core/doctype/doctype/doctype.js  3
> - frappe/integrations/doctype/google_calendar/google_calendar.py  21
> - frappe/core/doctype/session_default_settings/test_session_default_settings.py  1
> - frappe/database/mariadb/setup_db.py  6
> - frappe/social/doctype/post_comment/post_comment.py  3
> - frappe/patches/v12_0/move_timeline_links_to_dynamic_links.py  10
> - frappe/utils/oauth.py  3
> - frappe/core/doctype/data_import_beta/data_import_beta.py  5
> - frappe/core/doctype/version/version.py  1
> - frappe/website/doctype/personal_data_deletion_request/test_personal_data_deletion_request.py  1
> - frappe/public/js/frappe/web_form/web_form.js  8
> - frappe/public/js/frappe/form/controls/table_multiselect.js  6
> - frappe/desk/doctype/global_search_doctype/global_search_doctype.py  1
> - frappe/desk/doctype/tag/test_tag.py  1
> - frappe/public/js/frappe/form/controls/base_control.js  1
> - frappe/config/settings.py  1
> - frappe/website/doctype/personal_data_download_request/personal_data_download_request.py  3
> - frappe/email/utils.py  5
> - frappe/patches/v12_0/init_desk_settings.py  1
> - frappe/core/doctype/scheduled_job_type/test_scheduled_job_type.py  2
> - frappe/website/js/bootstrap-4.js  2
> - frappe/public/js/frappe/utils/help.js  4
> - frappe/core/doctype/doctype_link/doctype_link.py  1
> - frappe/core/doctype/comment/comment.py  11
> - frappe/public/js/frappe/utils/number_format.js  18
> - frappe/core/doctype/data_import/test_exporter_new.py  1
> - frappe/desk/doctype/notification_log/notification_log.js  1
> - frappe/website/web_form/request_to_delete_data/request_to_delete_data.py  1
> - frappe/patches/v12_0/create_notification_settings_for_user.py  2
> - frappe/integrations/doctype/webhook/test_webhook.py  1
> - frappe/public/js/frappe/form/controls/markdown_editor.js  3
> - frappe/public/js/frappe/utils/address_and_contact.js  5
> - frappe/core/doctype/data_import/exporter_new.py  11
> - frappe/public/js/frappe/ui/toolbar/tag_utils.js  3
> - frappe/utils/html_utils [...]

2020-01-14 12:02 UTC, Alchez requested changes
The feature works, but just make the suggested changes, and make it upstream

2020-01-14 12:02 UTC, Alchez commented on frappe/public/js/frappe/views/kanban/kanban_board.js
> +			var taskLink = frappe.utils.get_form_link(card.doctype, card.name);
```suggestion
			let task_ink = frappe.utils.get_form_link(card.doctype, card.name);
```

2020-01-14 12:02 UTC, Alchez commented on frappe/public/js/frappe/views/kanban/kanban_card.html
> +	<a class="clickable-link" href="#" target="_blank">
Change the class name to something specific to kanban cards

2020-01-14 12:04 UTC, Alchez commented
@Er-Naren719, not sure what's happening with Codacy, I think you can ignore them for now

2020-01-14 12:20 UTC, Er-Naren719 commented
> @Er-Naren719, not sure what's happening with Codacy, I think you can ignore them for now

Required changes are done. Please refer the latest commit.

2020-01-14 12:21 UTC, Alchez submitted a review, later dismissed

2020-01-15 10:09 UTC, Alchez approved these changes

2020-01-15 10:13 UTC, merged