fix: Web form child table new rows save
DigiThinkIT/frappe pull request #203
Opened 2020-03-09 07:48 UTC by nmimsnikhil

Web form child table value is now storing in parent table.
Before:
![Form_Child_Table](https://user-images.githubusercontent.com/56826544/76192620-45e33500-6208-11ea-91b7-1c483d97bfe0.gif)

After:
![Web_form_child_table](https://user-images.githubusercontent.com/56826544/76192628-4b407f80-6208-11ea-82b7-0bbed0dc7d72.gif)

2020-03-09 12:17 UTC, Alchez requested changes

2020-03-09 12:17 UTC, Alchez commented on frappe/public/js/frappe/form/grid.js
> +		if (!this.df.data){this.df.data = [];}
```suggestion
		this.df.data = this.df.data || [];
```

2020-03-09 12:17 UTC, Alchez commented on frappe/public/js/frappe/form/grid.js
> +		// this.remove_all();
Remove comment

2020-03-09 12:17 UTC, Alchez commented on frappe/public/js/frappe/form/grid.js
> +				var d = { idx: this.df.data.length + 1, __islocal: true, doctype: this.doctype, parentfield: this.df.fieldname, parenttype: frappe.web_form.doctype }
- Break this into multiple lines
- Use `const` instead of `var`
- Change the variable to `row`

2020-03-09 12:17 UTC, Alchez commented on frappe/public/js/frappe/form/grid.js
> +				if(!frappe.web_form.doc.hasOwnProperty(this.df.fieldname)) {
Let's just use the `in` operator to do this check:

```suggestion
				if (!(this.df.fieldname in frappe.web_form.doc)) {
```

2020-04-10 06:13 UTC, Alchez commented
This is fixed with https://github.com/frappe/frappe/pull/9851. Closing.

2020-04-10 06:13 UTC, closed without merging

2020-07-10 00:49 UTC, jseb16 commented
> This is fixed with [frappe#9851](https://github.com/frappe/frappe/pull/9851). Closing.

This didn't fix it in latest version-12 trying both solutions together