feat(frappe): email links of multiple docs
DigiThinkIT/frappe pull request #212
Opened 2020-04-01 15:19 UTC by MyuddinKhatri

multiple docs can be selected and link is generated with key to verify and is send in email instead of documents

2020-04-03 08:52 UTC, Alchez commented on frappe/desk/doctype/bulk_update/bulk_update.py
> +	if doctype == "Purchase Order":
I will test the logic separately, but these DocTypes won't be available in the Frappe app, so you might want to hook this function in ERPNext, and fetch the default contact there instead

2020-04-06 05:46 UTC, Alchez commented
Made upstream to [develop](https://github.com/frappe/frappe/pull/9837).

2020-04-09 06:08 UTC, neilLasrado requested changes

2020-04-09 06:08 UTC, neilLasrado commented on frappe/desk/doctype/bulk_update/bulk_update.py
> +	if doctype == "Purchase Order":
Yes, code in frappe should not refer to erpnext doctypes. please rework this.

2020-04-15 11:28 UTC, Alchez requested changes

2020-04-15 11:28 UTC, Alchez commented on frappe/public/js/frappe/list/list_view.js
> +				standard: false
Make this a standard button in the menu, place it just after `Print`

2020-04-15 11:28 UTC, Alchez commented on frappe/public/js/frappe/list/list_view.js
> +		if (has_email_permission(doctype)) {
Will `frappe.model.can_email(doctype)` not work?

2020-04-15 11:28 UTC, Alchez commented on frappe/public/js/frappe/list/bulk_operations.js
> +				if (doc.docstatus !== 1) {
Check if the doctype is submittable since non-submittable doctypes will always have a docstatus of 1.

I think you can check for the `doc.is_submittable` flag.

2020-04-15 11:28 UTC, Alchez commented on frappe/public/js/frappe/list/bulk_operations.js
> +					frappe.throw(__("Select only one customer's sales orders"))
This seems like it'll have very narrow context, since it may not apply to every doctype in the system.

I think a better flow would be to fallback to an empty recipient if documents from multiple parties are included.

2020-04-15 11:28 UTC, Alchez commented on frappe/public/js/frappe/list/bulk_operations.js
> +			frappe.call({
Maybe we can use `frappe.run_serially` for this instead

2020-04-15 11:28 UTC, Alchez commented on frappe/hooks.py
> +contact_fields = {
Move this to ERPNext's hooks

2020-04-15 11:28 UTC, Alchez commented on frappe/desk/doctype/bulk_update/bulk_update.py
> +			"key": frappe.get_doc(doctype, doc.get("name")).get_signature()
See if we can add an expiry to this link somehow, that'll be very important

2020-04-15 11:28 UTC, Alchez commented on frappe/desk/doctype/bulk_update/bulk_update.py
> +def get_contact(name, doctype):
The usual Frappe convention is to do `doctype, name` in order of db retrieval, let's stick to that

2020-04-15 11:28 UTC, Alchez commented on frappe/desk/doctype/bulk_update/bulk_update.py
> +def get_default_contact(out, name, doctype):
I think we should just have this function do one thing - fetch the default contact.

The processing that you're doing for the out variable can happen in the `get_contact` function itself.

2020-04-21 06:06 UTC, Alchez commented
Moved to https://github.com/DigiThinkIT/bloomstack_core/pull/185.

2020-04-21 06:06 UTC, closed without merging