feat(frappe): added authorizenet payment gateway to frappe integrations
DigiThinkIT/frappe pull request #215
Opened 2020-04-10 14:25 UTC by MyuddinKhatri

added authorizenet payment gateway to frappe integrations

2020-04-13 17:33 UTC, forellana-digithinkit commented
@MyuddinKhatri should someone be assigned to this for review?

2020-04-15 09:27 UTC, Alchez requested changes

2020-04-15 09:27 UTC, Alchez commented on frappe/templates/pages/integrations/authorizenet_checkout.html
> +    context: '{{ payment_context }}',
Is this actually being used? I don't see it being loaded or used on the checkout page?

2020-04-15 09:27 UTC, Alchez commented on frappe/templates/pages/integrations/authorizenet_checkout.html
> +
Remove all the extra whitespace in this file

2020-04-15 09:27 UTC, Alchez commented on frappe/templates/pages/integrations/authorizenet_checkout.html
> +    {% if image %}
You have the field available in Authorizenet Settings, just pull that in the .py file and pass it here through context

2020-04-15 09:27 UTC, Alchez commented on frappe/templates/includes/integrations/authorizenet_checkout.js
> +context = decodeURIComponent(url)
Check the `razorpay_checkout.js` file to see how to pass context to the client-side

2020-04-15 09:27 UTC, Alchez commented on frappe/templates/includes/integrations/authorizenet_checkout.js
> +	cardCode = document.getElementById('cardholder-cardCode').value;
We need to ensure this is getting passed securely, and not as plaintext. See if Frappe has any provision for this, otherwise we may just have to use Authorize.net's Simple Checkout buttons, and let them handle the security.

I'll talk to @forellana-digithinkit about this.

2020-04-15 09:27 UTC, Alchez commented on frappe/integrations/doctype/authorizenet_settings/authorizenet_settings.py
> +	supported_currencies = ["USD"]
They seem to also accept `CAD` in the US.

Ref: https://support.authorize.net/s/article/Which-Currencies-Does-Authorize-Net-Support

2020-04-15 09:27 UTC, Alchez commented on frappe/integrations/doctype/authorizenet_settings/authorizenet_settings.py
> +			frappe.throw(_("Please select another payment method. AuthozieNet does not support transactions in currency '{0}'").format(currency))
```suggestion
			frappe.throw(_("Please select another payment method. AuthorizeNet does not support transactions in currency '{0}'").format(currency))
```

2020-04-15 09:27 UTC, Alchez commented on frappe/integrations/doctype/authorizenet_settings/authorizenet_settings.py
> +	merchantAuth = apicontractsv1.merchantAuthenticationType()
Convert all the local [camelCase](https://en.wikipedia.org/wiki/Camel_case) variables to [snake_case](https://en.wikipedia.org/wiki/Snake_case) for Python

2020-04-15 09:27 UTC, Alchez commented on frappe/templates/pages/integrations/authorizenet_checkout.py
> +	payment_context = dict(frappe.local.request.args)
I don't think will work, try using `context.payment_context`

2020-04-17 04:27 UTC, DeveloperMetal requested changes

2020-04-17 04:27 UTC, forellana-digithinkit commented on frappe/templates/includes/integrations/authorizenet_checkout.js
> +	cardCode = document.getElementById('cardholder-cardCode').value;
So long the call is done through SSL and its a post, the only issues to worry about are logs on the server side.

2020-04-17 04:27 UTC, forellana-digithinkit commented on frappe/integrations/doctype/authorizenet_settings/authorizenet_settings.py
> +				print('Error Code: %s' %
please remove all these print statements.

2020-04-17 04:27 UTC, forellana-digithinkit commented on frappe/integrations/doctype/authorizenet_settings/authorizenet_settings.py
> +				print('Error Code: %s' % str(
You'll want to pass some of these to the user. Some of these errors range from invalid CVV to missing address information.

2020-04-22 11:20 UTC, Alchez commented
Moved to ERPNext integratons at https://github.com/DigiThinkIT/erpnext/pull/371.

2020-04-22 11:20 UTC, closed without merging