fix: on primary action callback close msgprint
DigiThinkIT/frappe pull request #225
Opened 2020-06-15 11:49 UTC by vishdha

Task ID: https://bloomstack.com/desk#Form/Task/TASK-2020-00117

2020-06-15 12:10 UTC, Alchez commented on frappe/public/js/frappe/ui/messages.js
> +						console.log("sucess")
Remove the console.log and put it upstream, see what they think

2020-06-15 12:53 UTC, Alchez commented on frappe/public/js/frappe/ui/messages.js
> +						frappe.hide_msgprint();
To get more dev control, I think you should also add a `callback` property in `data.primary_action`. That way, we can do whatever we want during callback. This is too restrictive.

2020-06-15 14:32 UTC, vishdha commented
upstream: https://github.com/frappe/frappe/pull/10693

2020-06-16 06:42 UTC, Alchez requested changes

2020-06-16 06:42 UTC, Alchez commented on frappe/public/js/frappe/ui/messages.js
> +								() => frappe.msgprint(r.message, title="sucess")
```suggestion
								() => frappe.msgprint(r.message, title="Success")
```

2020-06-16 06:42 UTC, Alchez commented on frappe/public/js/frappe/ui/messages.js
> +						if (r) {
```suggestion
						if (r && r.message) {
```

2020-06-16 09:16 UTC, Alchez submitted a review, later dismissed

2020-06-18 06:16 UTC, Alchez requested changes

2020-06-18 06:16 UTC, Alchez commented on frappe/__init__.py
> +		out.hide_on_success = 1
The `hide_on_success` is contextual to the primary action, it should be a part of that object

2020-06-18 06:16 UTC, Alchez commented on frappe/public/js/frappe/ui/messages.js
> +							if (data.hide_on_success) {
Let's keep it simple, see if this works

```
if (data.primary_action.hide_on_success) {
	hide_msgprint();
}

if (r && r.message) {
	frappe.msgprint();
}
```

2020-06-18 08:26 UTC, vishdha commented
upstream: https://github.com/frappe/frappe/pull/10729

2020-06-18 08:32 UTC, Alchez approved these changes

2020-06-18 08:41 UTC, merged