Added close button for full screen chat
DigiThinkIT/frappe pull request #254
Opened 2020-09-01 12:28 UTC by vigilantee

Task ID:
https://bloomstack.com/desk#Form/Task/TASK-2020-01521

2020-09-03 10:19 UTC, hrwX commented
-    @vigilantee Can we replace the `X` with `fa-times` fontawesome icon ? 
-    It'll look consistent with the other two button too since this close button looks way different than the neighbouring buttons.
         ![image](https://user-images.githubusercontent.com/7310479/92102969-f3708300-edfc-11ea-87dd-f958dbd30022.png)
-    Since you are anyway adding a button for expanded view, might as well change it for the smaller view

2020-09-07 12:02 UTC, Alchez commented
@vigilantee, is this ready for review? Or are you still making changes?

2020-10-19 05:30 UTC, hrwX requested changes

2020-10-19 05:30 UTC, hrwX commented on frappe/public/js/frappe/chat.js
> +	console.log(fn);
```suggestion
```

2020-10-19 05:30 UTC, hrwX commented on frappe/public/js/frappe/chat.js
> +					if(update.seen) {
```suggestion
					if (update.seen) {
```

2020-10-19 05:30 UTC, hrwX commented on frappe/public/js/frappe/chat.js
> +				if(update.seen) {
```suggestion
				if (update.seen) {
```

2020-10-19 05:30 UTC, hrwX commented on frappe/public/js/frappe/chat.js
> +		console.log("binding");
```suggestion
```

2020-10-19 05:30 UTC, hrwX commented on frappe/public/js/frappe/chat.js
> +					// }
```suggestion
```

2020-11-05 10:47 UTC, closed without merging

2020-11-05 10:48 UTC, hrwX commented
Closing this PR since a new PR is up #300