Fix/chat issues
DigiThinkIT/frappe pull request #260
Opened 2020-09-10 09:44 UTC by jitendraharpalani

https://bloomstack.com/desk#Form/Task/TASK-2020-01520
https://bloomstack.com/desk#Form/Task/TASK-2020-00259
https://bloomstack.com/desk#Form/Task/TASK-2020-01521
https://bloomstack.com/desk#Form/Task/TASK-2020-01522

Summary
https://bloomstack.com/desk#Form/Task/TASK-2020-01097

2020-09-18 13:24 UTC, hrwX requested changes

2020-09-18 13:24 UTC, hrwX commented on frappe/public/js/frappe/chat.js
> +			 */
- If this is not required then lets remove it ?

2020-09-18 13:24 UTC, hrwX commented on frappe/public/js/frappe/chat.js
> +					<span class="notifications-indicator" style="display: none; color: red; font-size:10px; top: 0; right: 5px" id="unread_message_indicator">
- We can show a similar indicator just like the one notification icon has right ??
- The red color is kinda looking out of place.

2020-09-18 13:24 UTC, hrwX commented on frappe/public/js/frappe/chat.js
> +					// }
- Remove this too

2020-09-18 13:24 UTC, hrwX commented on frappe/public/js/frappe/chat.js
> +								}, "X"),
can we add an octicon here ?? the `X` looks bad

![image](https://user-images.githubusercontent.com/7310479/93602486-4abb4980-f9e0-11ea-8cc3-a649d0611460.png)

2020-10-19 06:01 UTC, vigilantee commented on frappe/public/js/frappe/chat.js
> +			 */
We will be replacing the chat module in the near so we might need this for reference.

2020-10-19 06:02 UTC, vigilantee approved these changes

2020-10-28 08:42 UTC, hrwX commented
Closing this PR since a version of this has been merged in develop

2020-10-28 08:42 UTC, closed without merging