Added endpoints for aws sign in url
DigiThinkIT/frappe pull request #269
Opened 2020-10-05 09:33 UTC by vigilantee

Changes for cognito sign in URL generation.

2020-10-05 17:59 UTC, hrwX requested changes

2020-10-05 17:59 UTC, hrwX commented on frappe/integrations/oauth2.py
> +			failure_url = frappe.form_dict["cmd"] + "?error=access_denied"
- why overriding `failure_url` if the request has `cmd` ?
- `cmd` parameter is mainly consists of dot path to python function

2020-10-05 17:59 UTC, hrwX commented on frappe/integrations/oauth2_logins.py
> +
- Why not use `custom` function defined for Social Login ?? 
- We can create custom social login in every instance via `bloomtrace_core`.

2020-10-05 17:59 UTC, hrwX commented on frappe/utils/oauth.py
> +			"last_name": get_last_name(data) or "",
```suggestion
			"last_name": get_last_name(data),
```
- `last_name` is not mandatory

2020-10-05 17:59 UTC, hrwX commented on frappe/utils/oauth.py
> +			"first_name": get_first_name(data) or data["email"],
```suggestion
			"first_name": get_first_name(data) or get_email(data),
```

2020-10-06 03:11 UTC, vigilantee commented on frappe/integrations/oauth2.py
> +			failure_url = frappe.form_dict["cmd"] + "?error=access_denied"
For our use case the redirect_uri is not passed to tackle that we have made this change.

2020-10-06 03:11 UTC, vigilantee commented on frappe/integrations/oauth2_logins.py
> +
For the cognito sign in we need to get the link for aws sign in and redirect_to is passed in the urlencoded way so we had to intercept the request and make some changes in this.

2020-10-06 05:05 UTC, hrwX requested changes

2020-10-06 05:05 UTC, hrwX commented on frappe/integrations/oauth2.py
> +			failure_url = frappe.form_dict["cmd"] + "?error=access_denied"
```suggestion
	failure_url = (frappe.form_dict["redirect_uri"] or frappe.form_dict["cmd"] or "") + "?error=access_denied"
```

2020-10-06 06:59 UTC, hrwX approved these changes

2020-10-06 07:11 UTC, jitendraharpalani approved these changes

2020-10-06 08:27 UTC, merged