B aws endpoint
DigiThinkIT/frappe pull request #285
Opened 2020-10-19 05:51 UTC by vigilantee

In reference to the AWS sign in flow for multi server authentication.

2020-10-19 05:53 UTC, hrwX approved these changes

2020-11-05 10:48 UTC, hrwX commented
@vigilantee Fix the name of the PR as well as the commit messages for this to be merged.

2020-11-05 10:51 UTC, hrwX requested changes

2020-11-05 10:51 UTC, hrwX commented on frappe/utils/oauth.py
> +			"last_name": get_last_name(data) or "",
```suggestion
			"last_name": get_last_name(data),
```
Return empty string from the get_last_name function

2020-11-16 15:04 UTC, neilLasrado commented
@vigilantee Can you please implement the changes suggested by Himanshu? and fix your commit messages

2020-11-26 10:55 UTC, neilLasrado commented
@vigilantee whats going on with this PR?

2020-12-04 04:49 UTC, hrwX commented
@vigilantee Please make the changes asap, else I will be closing this PR

2020-12-07 06:42 UTC, neilLasrado commented
@vigilantee what is going on with this?

2020-12-11 11:46 UTC, vigilantee commented
@neilLasrado @hrwX closing this PR as the merge won't be required as last name is not mandatory for aws auth flow now.

2020-12-14 04:39 UTC, vigilantee commented on frappe/utils/oauth.py
> +			"last_name": get_last_name(data) or "",
@hrwX Not required in the current aws login flow. So we can close this PR.

2020-12-14 10:44 UTC, closed without merging