Chat Issue fixes Consolidated PR
DigiThinkIT/frappe pull request #286
Opened 2020-10-19 06:13 UTC by vigilantee

Reference for this PR: https://github.com/Bloomstack/frappe/pull/260
This PR is already reviewed but had to open a new PR with same file changes for the new develop in upstream.

2020-10-19 06:41 UTC, hrwX requested changes

2020-10-19 06:41 UTC, hrwX commented on frappe/public/js/frappe/chat.js
> +
```suggestion

```

2020-10-19 06:43 UTC, hrwX submitted a review, later dismissed

2020-10-19 17:15 UTC, hrwX approved these changes

2020-10-26 06:09 UTC, sahil28297 approved these changes

2020-10-26 06:10 UTC, merged