feat: generate redirect to automatically
DigiThinkIT/frappe pull request #303
Opened 2020-10-30 09:28 UTC by hrwX

https://app.asana.com/0/1188976263154030/1198950940677093

2020-10-31 10:27 UTC, jitendraharpalani requested changes

2020-10-31 10:27 UTC, jitendraharpalani commented on frappe/integrations/oauth2_logins.py
> +	if not redirect_to and frappe.get_cached_value("OAuth Client", {"app_name": "Bloomstack"}, "client_id") and frappe.get_hooks("bloomstack_redirect_uri"):
@hrwX App name will be Frappe for this one.

2020-10-31 10:27 UTC, jitendraharpalani commented on frappe/integrations/oauth2_logins.py
> +			frappe.get_hooks("bloomstack_redirect_uri"))
@hrwX sorry I just realized that OAuth Client doctype already has a Redirect URL which is something we can use. 
Ref: https://demo.bloomstack.garden/desk#Form/OAuth%20Client/b0356dedd8

2020-11-02 06:24 UTC, jitendraharpalani requested changes

2020-11-02 06:24 UTC, jitendraharpalani commented on frappe/integrations/oauth2_logins.py
> +			redirect_uri={2}".format(frappe.utils.get_url(), client.get("client_id"), client.get("redirect_uris"))
better would be to use default redirect URI as the user can define multiple URLs in redirect URIs.

2020-11-02 08:09 UTC, jitendraharpalani approved these changes

2020-11-16 15:18 UTC, neilLasrado approved these changes

2020-11-16 15:31 UTC, merged