fix: frappe listing template fixed
DigiThinkIT/frappe pull request #305
Opened 2020-11-02 11:58 UTC by nehasacher143

**Task:** Fix the listing template, so that, even if we have nothing to show.

2020-11-04 14:32 UTC, DeveloperMetal reviewed
@nehasacher143 What's this PR about?
Are you making the header appear when there are no results?

What are the side effects on the rest of the system?

2020-11-05 12:29 UTC, nehasacher143 commented
Hey @DeveloperMetal 
Yes, I am trying to make the header appear, when there are no results.
I guess this won't have any adverse effects on the rest of the site, as it will only work if we have this in Context, and for now we are only using it for our new website design

2020-11-09 08:15 UTC, hrwX requested changes

2020-11-09 08:15 UTC, hrwX commented on frappe/templates/includes/list/list.html
> +{% if result_heading_template %}{% include result_heading_template %}{% endif %}
- Do not use `result heading template` variable here, as the name suggests that the template is for result
- You can add a new variable `page heading template` to achieve this

2020-11-10 04:03 UTC, nehasacher143 commented
Hey @hrwX Please review this

2020-11-10 05:27 UTC, hrwX approved these changes

2020-11-10 05:27 UTC, merged