feat: Assign to multiple people at once
DigiThinkIT/frappe pull request #306
Opened 2020-11-03 04:39 UTC by vishdha

Currently, while assigning a document, you could only assign one person at a time, which made it a task to assign it to multiple people as you had to repeat the whole process multiple times.
In this PR, you can now assign to multiple people at once, which is achieved using MultiSelectPills.

Credit:
@hwx

2020-11-03 08:32 UTC, hrwX requested changes

2020-11-03 08:32 UTC, hrwX commented on frappe/public/js/frappe/form/sidebar/assign_to.js
> +				let args = me.dialog.get_values();
```suggestion
							let txt = this.$input.val();
							data = this.df.get_data(txt);
```
https://github.com/frappe/frappe/pull/10412

2020-11-04 16:36 UTC, hwx commented
> Credit:
> @hwx

please remove me @hwx from the comments
appreciate

2020-11-05 05:47 UTC, vishdha commented on frappe/public/js/frappe/form/sidebar/assign_to.js
> +				let args = me.dialog.get_values();
@hrwX  not needed. get_values do there work

2020-11-05 12:25 UTC, hrwX approved these changes

2020-11-16 10:19 UTC, sahil28297 approved these changes

2020-11-16 10:19 UTC, merged