feat(ListView): allow overriding columns from settings
DigiThinkIT/frappe pull request #317
Opened 2020-11-05 08:27 UTC by nmimsnikhil

- Rename List View Setting to List View Settings.
- Allow overriding ListView total number of display columns from Settings in ListView.
- Use 1366 and 1920 as screen width breakpoints for deciding total number of columns.
- Allow rearranging of column order from List View Settings. (Title/Name column can't be rearranged)

ref: https://app.asana.com/0/1198992588740629/1198992588740642

![list_view](https://user-images.githubusercontent.com/56826544/98215960-7386a680-1f6e-11eb-9c1a-7df18dde43d5.gif)

2020-11-10 05:24 UTC, hrwX requested changes

2020-11-10 05:24 UTC, hrwX commented on frappe/desk/doctype/list_view_settings/list_view_settings.py
> +		if not meta.title_field.strip() in fields:
```suggestion
	if meta.title_field and not meta.title_field.strip() in fields:
```

2020-11-16 15:38 UTC, neilLasrado commented
@nmimsnikhil is this something only system managers will be able to do?

2020-11-20 04:42 UTC, nmimsnikhil commented
> @nmimsnikhil is this something only system managers will be able to do?

Sorry @neilLasrado for late reply. No, this can be done by anyone

2020-11-26 11:05 UTC, neilLasrado submitted a review, later dismissed

2020-11-26 11:05 UTC, neilLasrado commented on frappe/desk/doctype/list_view_settings/list_view_settings.json
> +   "role": "System Manager",
Please add all the relevant permission roles. Else this will give permission error for non-system managers

2020-12-02 04:52 UTC, hrwX commented on frappe/desk/doctype/list_view_settings/list_view_settings.json
> +   "role": "System Manager",
- This doctype is not visible via Global Search
- Also only System Users can see the setting for changing columns

2020-12-04 09:39 UTC, hrwX approved these changes

2020-12-04 09:40 UTC, merged