feat(form): added set_root_read_only form api
DigiThinkIT/frappe pull request #318
Opened 2020-11-05 09:52 UTC by vishdha

2020-11-05 10:11 UTC, hrwX requested changes

2020-11-05 10:11 UTC, hrwX commented on frappe/public/js/frappe/form/form.js
> +			this.set_intro(__("This is a root supplier group and cannot be edited."), true);
- Dont reference ERPNext into Frappe.
- Frappe is independent of ERPNext

2020-11-05 10:15 UTC, vishdha commented on frappe/public/js/frappe/form/form.js
> +			this.set_intro(__("This is a root supplier group and cannot be edited."), true);
we dont have any erpnext reference

2020-11-05 10:19 UTC, hrwX requested changes

2020-11-05 10:19 UTC, hrwX commented on frappe/public/js/frappe/form/form.js
> +			this.set_intro(__("This is a root {0} and cannot be edited.", [this.doc.doctype.toLowerCase()]), true);
```suggestion
			this.set_intro(__("This is a root {0} and cannot be edited.", [this.doc.doctype]), true);
```

2020-11-05 10:19 UTC, hrwX commented on frappe/public/js/frappe/form/form.js
> +	}
- Run this function is the doctype has treeview enabled.

2020-11-05 10:33 UTC, vishdha commented on frappe/public/js/frappe/form/form.js
> +			this.set_intro(__("This is a root {0} and cannot be edited.", [this.doc.doctype.toLowerCase()]), true);
removing this does not look good 
for eg.
This is a root Supplier Group and cannot be edited

2020-11-11 06:13 UTC, hrwX requested changes

2020-11-11 06:13 UTC, hrwX commented on frappe/public/js/frappe/form/form.js
> +			this.set_intro(__("This is a root {0} and cannot be edited.", [this.doc.doctype.toLowerCase()]), true);
- We want the Supplier Group to stand out because the provides context to the intro
- Maybe we can add a bold or something.

2020-11-11 06:17 UTC, hrwX requested changes

2020-11-11 06:17 UTC, hrwX commented on frappe/public/js/frappe/form/form.js
> +		if(this.meta.is_tree && (!this.doc[fieldname] && !this.is_new())) {
```suggestion
		if (this.meta.is_tree && !this.doc[fieldname] && !this.is_new()) {
```

2020-11-11 06:17 UTC, hrwX commented on frappe/public/js/frappe/form/form.js
> +			this.set_intro(__("This is a root {0} and cannot be edited.", [this.doc.doctype.toLowerCase()]), true);
```suggestion
			this.set_intro(__("This is a root {0} and cannot be edited.", [this.doc.doctype.bold()]), true);
```

2020-11-11 06:23 UTC, vishdha commented on frappe/public/js/frappe/form/form.js
> +			this.set_intro(__("This is a root {0} and cannot be edited.", [this.doc.doctype.toLowerCase()]), true);
This needs to be lowercase

2020-11-16 11:38 UTC, sahil28297 approved these changes

2020-11-16 11:39 UTC, merged