Feat image processing
DigiThinkIT/frappe pull request #327
Opened 2020-11-09 19:04 UTC by DeveloperMetal

Adds dynamic image generation for the purpose of handling thumbnail resizing.
Adds caching of these generated images so only the first requests builds the image.

To generate a thumbnail of /file/myimage.jpg and resize to 400x400 pixels you would use:

/thumbnail/myimage.jpg?size=400

There are multiple options to choose from:

	Examples: 
	
	/thumbnail/myimage.jpg?size=300&resample=0&quality=20
	/thumbnail/myimage.jpg?width=300&resample=0&quality=20
	/thumbnail/myimage.jpg?height=300&resample=0&quality=20
	/thumbnail/myimage.jpg?width=200&height=300&resample=0&quality=20

	Options:

		- width: The maximum image width desired in pixels.

		- height: The maximum image height desired in pixels.

		- size: A single value for maximum image width and height desired in pixels.

		- resample: Sampling filter value from 0 to 5. See below from worst(fastest) to best(slowest).
			Defaults to 2 - BILINEAR:

			- 0: Nearest - Pick one nearest pixel from the input image. Ignore all other input pixels.
			- 1: Box - Each pixel of source image contributes to one pixel of the destination image with identical weights
			- 2: Bilinear - For resize calculate the output pixel value using linear interpolation on all pixels that may contribute to the output value
			- 3: Hamming - Produces a sharper image than BILINEAR, doesn’t have dislocations on local level like with BOX.
			- 4: Bicubic - For resize calculate the output pixel value using cubic interpolation on all pixels that may contribute to the output value
			- 5: Lanczos - Calculate the output pixel value using a high-quality Lanczos filter (a truncated sinc) on all pixels that may contribute to the output value

		- quality: For JPG images from 0(smallest files size) worst to 100(largest file size) best. Defaults to 75

One issue we might see however is that this opens us up for abuse. You could conceivably issue multiple requests increasing image size to force a cache depletion.

Perhaps adding a new doctype to store preset resize options would be a better alternative than allow modifying these options directly? What do you guys think?

2020-11-10 05:18 UTC, hrwX commented
@sahil28297 create instance

2020-11-10 05:20 UTC, sahil28297 commented
@sahil28297 create instance

2020-11-10 05:26 UTC, sahil28297 commented
@sahil28297 create instance

2020-11-10 11:10 UTC, Alchez requested changes

2020-11-10 11:10 UTC, Alchez commented on frappe/utils/image.py
> +	][cint(commands.resample or 2)]
Should this be a comment/reference instead? I don't think we need to do this extra processing, since the constants resolve to integers anyway

2020-11-10 11:10 UTC, Alchez commented on frappe/utils/image.py
> +	extn = path.rsplit('.', 1)[-1]
This is only for readability (and maybe some additional reliability), but you could use `os` for this:

```suggestion
	filename, extn = os.path.splitext(path)
	extn = extn.replace(".", "")
```

2020-11-10 11:10 UTC, Alchez commented on frappe/utils/image.py
> +	img.save(buffer,
This can raise an `OSError` on failing to [save](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.save). Should we handle that too?

2020-11-10 13:59 UTC, DeveloperMetal commented on frappe/utils/image.py
> +	img.save(buffer,
Hmm... Yeah I'll wrap it on a try catch tho this isn't saving on disk its a in memory allocation. The server should be crashing by the time we can't allocate an image.

2020-11-10 14:11 UTC, DeveloperMetal commented on frappe/utils/image.py
> +	][cint(commands.resample or 2)]
What if they change the flag values in the future or add extra filters? Was thinking I didn't want older setups to break due to an update.

2020-11-10 14:33 UTC, Alchez commented on frappe/utils/image.py
> +	][cint(commands.resample or 2)]
Oh, I see what you mean. I would think that could be resolved with version-locking, since this is an external dependency, but this could be an additional check too.

2020-11-10 14:34 UTC, Alchez commented on frappe/utils/image.py
> +	img.save(buffer,
Oh did not know that, then I think this can go without the change

2020-11-10 14:44 UTC, DeveloperMetal commented on frappe/utils/image.py
> +	extn = path.rsplit('.', 1)[-1]
Copied this from frappe codebase, but alas doesn't os.path.splitext split on every dot? would have to add extra logic to capture the very last extension

2020-11-10 14:56 UTC, Alchez commented on frappe/utils/image.py
> +	extn = path.rsplit('.', 1)[-1]
It would actually only pick up the last one:

```python
>>> os.path.splitext("/path/to/file.tar.gz")
('/path/to/file.tar', '.gz')
```

2020-11-10 18:37 UTC, DeveloperMetal commented on frappe/utils/image.py
> +	extn = path.rsplit('.', 1)[-1]
Sweet, updating it

2020-11-10 21:57 UTC, neilLasrado commented on frappe/desk/page/setup_wizard/install_fixtures.py
> +		{"preset_name": "medium", "width": 250, "height": 250, "resample": "Bilinear", "quality": 75},
Small and Medium presets seem to be same, is that intentional?

2020-11-10 21:59 UTC, neilLasrado submitted a review, later dismissed
Rest looks good.

2020-11-11 00:45 UTC, DeveloperMetal commented on frappe/desk/page/setup_wizard/install_fixtures.py
> +		{"preset_name": "medium", "width": 250, "height": 250, "resample": "Bilinear", "quality": 75},
Fixed

2020-11-12 11:09 UTC, neilLasrado approved these changes

2020-11-12 13:18 UTC, merged