feat: added Kanban Quick Card
DigiThinkIT/frappe pull request #329
Opened 2020-11-12 11:43 UTC by bhattdevarsh

![kanban_card](https://user-images.githubusercontent.com/58166671/98935937-486dfb00-250a-11eb-958e-ccac37d34685.gif)

2020-11-16 13:01 UTC, hrwX requested changes

2020-11-16 13:01 UTC, hrwX commented on frappe/public/js/frappe/views/kanban/kanban_board.js
> +			frappe.throw(__("Pelase provide Document Type and/or Document Name"))
```suggestion
			frappe.throw(__("Document not found."));
```

2020-11-16 13:01 UTC, hrwX commented on frappe/public/js/frappe/views/kanban/kanban_board.js
> +			});
- Check if you can show all the fields in dialog.
- Also check if we can show table in dialog.

2020-11-16 13:01 UTC, hrwX commented on frappe/public/js/frappe/views/kanban/kanban_board.js
> +			});
- Show all the fields

2020-11-26 11:10 UTC, neilLasrado commented
@bhattdevarsh its been 10 days since Himanshu gave a review. Please take this up on priority.

2020-11-26 11:32 UTC, bhattdevarsh commented
> @bhattdevarsh its been 10 days since Himanshu gave a review. Please take this up on priority.

hey @neilLasrado, Me and himanshu have discussed on this. as of now i continue working on client request and bugs for that reason This feature building has been kept on halt.

2020-12-05 09:52 UTC, hrwX requested changes

2020-12-05 09:52 UTC, hrwX commented on frappe/desk/doctype/kanban_board/kanban_board.py
> +def on_submit_kanban_dialog(docname,doctype,values):
```suggestion
def on_submit_kanban_dialog(docname, doctype, values):
```

2020-12-05 09:52 UTC, hrwX commented on frappe/desk/doctype/kanban_board/kanban_board.py
> +	task_doc = frappe.get_doc(doctype,docname)
```suggestion
	task_doc = frappe.get_doc(doctype, docname)
```

2020-12-05 09:52 UTC, hrwX commented on frappe/public/js/frappe/views/kanban/kanban_board.js
> +			this.mandatory.push({ fieldtype: 'Link', fieldname: 'assign_to', options: 'User', label: __("Assign To"), reqd: false, filters: { 'user_type': 'System User' } });
```suggestion
			this.mandatory.push({ fieldtype: 'MultiSelectPills', fieldname: 'assign_to', options: 'User', label: __("Assign To"), reqd: false, filters: { 'user_type': 'System User' } });
```

2020-12-05 09:52 UTC, hrwX commented on frappe/public/js/frappe/views/kanban/kanban_board.js
> +	create_edit_dialog() {
```suggestion
	create_dialog() {
```

2020-12-05 09:52 UTC, hrwX commented on frappe/public/js/frappe/views/kanban/kanban_board.js
> +				}
- Call `assign_to.add` from `on_submit_kanban_dialog`, do not make a new `frappe.call`

2020-12-07 04:40 UTC, hrwX requested changes

2020-12-07 04:40 UTC, hrwX commented on frappe/desk/doctype/kanban_board/kanban_board.py
> +	value = json.loads(values)
```suggestion
	values = json.loads(values)
```

2020-12-07 04:40 UTC, hrwX commented on frappe/desk/doctype/kanban_board/kanban_board.py
> +	task_doc = frappe.get_doc(doctype, docname)
```suggestion
	doc = frappe.get_doc(doctype, docname)
```

2020-12-07 04:40 UTC, hrwX commented on frappe/desk/doctype/kanban_board/kanban_board.py
> +		updates.update({key: value[key]})
```suggestion
	assignees = values.pop("assign_to")
	add(assignees)
```

2020-12-07 04:40 UTC, hrwX commented on frappe/desk/doctype/kanban_board/kanban_board.py
> +	args = {}
```suggestion
```

2020-12-07 04:40 UTC, hrwX commented on frappe/desk/doctype/kanban_board/kanban_board.py
> +	task_doc.save()
```suggestion
	doc.update(updates)
	doc.save()
```

2020-12-07 04:55 UTC, bhattdevarsh commented
@hrwX , these suggestions seems sorted. but we need the keys to map from values to the doc.
and also we are removing `updates = {}` so now we cannot do doc.update(updates)

2020-12-07 04:59 UTC, hrwX commented
> @hrwX , these suggestions seems sorted. but we need the keys to map from values to the doc.
> and also we are removing `updates = {}` so now we cannot do `doc.update(updates)`

The values are being sent in a dict.

2020-12-08 05:31 UTC, hrwX approved these changes, later dismissed

2020-12-08 05:31 UTC, hrwX commented on frappe/core/report/permitted_documents_for_user/permitted_documents_for_user.py
> -		columns = columns + ["Read", "Write", "Create", "Delete", "Submit", "Cancel", "Amend", "Print", "Email",
Do not import rights from permission.py, revert this code change

2020-12-08 05:31 UTC, hrwX commented on frappe/core/report/permitted_documents_for_user/permitted_documents_for_user.py
> +# @frappe.validate_and_sanitize_search_inputs
```suggestion
```

2020-12-08 05:31 UTC, hrwX commented on frappe/core/report/permitted_documents_for_user/permitted_documents_for_user.py
> +	can_read = user_perms.can_read # Does not include child tables
Why are there changes to permitted_documents ?

2020-12-08 05:31 UTC, hrwX commented on frappe/public/js/frappe/views/kanban/kanban_board.js
> +				if (field.fieldtype != "Table MultiSelects" && field.fieldtype != "Table") {
Can you try Table field too in dialog, since they support Tables in dialog

2020-12-08 05:35 UTC, hrwX commented
@bhattdevarsh Please make the changes

2020-12-09 09:27 UTC, bhattdevarsh commented on frappe/public/js/frappe/views/kanban/kanban_board.js
> +				if (field.fieldtype != "Table MultiSelects" && field.fieldtype != "Table") {
as Discussed, its still showing the same error for table. so closing this comment

2020-12-09 10:29 UTC, hrwX requested changes

2020-12-09 10:29 UTC, hrwX commented on frappe/public/js/frappe/views/kanban/kanban_board.js
> +				if (field.fieldtype != "Table MultiSelects" && field.fieldtype != "Table") {
```suggestion
				if (field.fieldtype != "Table MultiSelect" && field.fieldtype != "Table") {
```

2020-12-09 10:29 UTC, hrwX commented on frappe/public/js/frappe/views/kanban/kanban_board.js
> +			});
Can we push all the fields to dialog except mandatory ones

2020-12-09 10:29 UTC, hrwX commented on frappe/public/js/frappe/views/kanban/kanban_board.js
> +			title: 'Enter details',
```suggestion
			title: __("{0}: {1}", [this.doctype, this.docname]),
```

2020-12-09 10:29 UTC, hrwX commented on frappe/desk/doctype/kanban_board/kanban_board.py
> +	add(args)
```suggestion
	add({
		"doctype": doctype,
		"name": docname,
		"assign_to": assignees
	})
```

2020-12-09 11:31 UTC, bhattdevarsh commented on frappe/public/js/frappe/views/kanban/kanban_board.js
> +			});
@hrwX we cannot have all the fields here, as it contains table as well. and we may also lose the essence of Quick Entry.

2020-12-10 03:26 UTC, hrwX approved these changes

2020-12-10 03:26 UTC, merged