feat: blog listing page resdesigned
DigiThinkIT/frappe pull request #340
Opened 2020-11-24 11:13 UTC by nehasacher143

Task: Redesign/Revamp the frappe blog page

Screenshot: 
![screenshot-localhost_8005-2020 11 24-16_43_18](https://user-images.githubusercontent.com/45919049/100087044-2ebaa500-2e74-11eb-8373-340dda9dba2b.png)

2020-11-24 16:27 UTC, DeveloperMetal submitted a review, later dismissed
Can you post a picture of a vanilla frappe instance running the blog instead of your local bloomstack copy please?

We need to make sure vanilla still looks decent. Any other customizations to specific sites are a separate thing.

2020-11-24 17:44 UTC, nehasacher143 commented
Hey @DeveloperMetal I have updated the PR with vanilla frappe screenshot

2020-11-26 10:54 UTC, neilLasrado requested changes

2020-11-26 10:54 UTC, neilLasrado commented on frappe/hooks.py
> +blogs_page_heading_template = 'website/doctype/blog_post/templates/blog_post_header.html'
Why are you adding a hook, you can directly update the frappe code right? 
@hrwX can you confirm this?

2020-11-26 10:54 UTC, neilLasrado commented on frappe/website/doctype/blog_post/blog_post.py
> +		featured_doc = get_featured_doc(),
the variable should be called featured_blog why featured_doc?

2020-11-26 10:54 UTC, neilLasrado commented on frappe/website/doctype/blog_post/blog_post.py
> +		background_image = frappe.db.get_single_value('Website Settings', 'blog_header')
you are doing a get_value inside the get_featured_doc function as well. Just do get doc website settings once and assign the variables. Always optimize database calls, especially for website context.

2020-11-26 11:05 UTC, hrwX requested changes

2020-11-26 11:05 UTC, hrwX commented on frappe/website/doctype/blog_post/blog_post.py
> +		page_heading_template = frappe.get_hooks('blogs_page_heading_template') or '',
```suggestion
		page_heading_template = frappe.get_hooks('blogs_page_heading_template') or 'website/doctype/blog_post/templates/blog_post_header.html',
```

2020-11-26 11:05 UTC, hrwX commented on frappe/website/doctype/blog_post/blog_post.py
> +	return featured_doc
```suggestion
	featured = frappe.db.get_single_value('Website Settings', 'featured_blog')
	featured_doc = frappe.get_doc("Blog Post", featured)
	return featured_doc
```

Can we make featured blog check inside a blog rather than `Website Settings` ?

2020-11-26 11:07 UTC, nehasacher143 commented on frappe/website/doctype/blog_post/blog_post.py
> +	return featured_doc
This was @neilLasrado's take 
@neilLasrado How do u want it

2020-11-26 11:07 UTC, hrwX commented on frappe/hooks.py
> +blogs_page_heading_template = 'website/doctype/blog_post/templates/blog_post_header.html'
- She might have got confused since I have told her to add a hook so that we can add `page_heading` directly from our custom app.
- Told her to make the relevant changes

2020-11-26 11:08 UTC, neilLasrado commented on frappe/website/doctype/blog_post/blog_post.py
> +	return featured_doc
Only one blog can be a featured blog. Website settings still might be a better place? what do you think?

2020-11-26 11:34 UTC, neilLasrado requested changes

2020-11-26 11:34 UTC, neilLasrado commented on frappe/website/doctype/blog_post/blog_post.py
> +		featured_blog = get_featured_doc(website_settings),
pass website_settings.get("featured_blog")

2020-11-26 11:34 UTC, neilLasrado commented on frappe/website/doctype/blog_post/blog_post.py
> +		featured_blog = get_featured_doc(website_settings),
instead of the whole document

2020-11-26 11:34 UTC, neilLasrado commented on frappe/website/doctype/blog_post/blog_post.py
> +	featured_doc = frappe.get_doc("Blog Post", website_settings.get("featured_blog"))
this will return a new doc if the featured blog is not set under website settings, while that not break your context?

2020-11-26 11:34 UTC, neilLasrado commented on frappe/website/doctype/blog_post/blog_post.py
> +		page_heading_template = frappe.get_hooks('blogs_page_heading_template') or 'website/doctype/blog_post/templates/blog_post_header.html',
set this only if there is a featured blog set in the website settings?

2020-11-26 11:51 UTC, nehasacher143 commented on frappe/website/doctype/blog_post/blog_post.py
> +		page_heading_template = frappe.get_hooks('blogs_page_heading_template') or 'website/doctype/blog_post/templates/blog_post_header.html',
We can always have a banner image even if no featured article

2020-11-26 12:53 UTC, neilLasrado submitted a review, later dismissed

2020-11-27 09:06 UTC, vigilantee requested changes

2020-11-27 09:06 UTC, vigilantee commented on frappe/public/css/blogheader.css
> +  margin-top: 0!important;
Can we remove "!important" and still achieve the design?

2020-11-27 09:06 UTC, vigilantee commented on frappe/public/css/blogheader.css
> +  margin-top: 0!important;
!important attribute coming from frappe and hence can't change it.

2020-11-27 09:06 UTC, vigilantee commented on frappe/public/css/blogheader.css
> +  padding-top: 11.0625rem;
Limit this upto 3 digits post decimal.

2020-11-27 09:06 UTC, vigilantee commented on frappe/public/css/blogheader.css
> +}
New line.

2020-11-27 09:06 UTC, vigilantee commented on frappe/website/css/blog.css
> +  margin-left: -15px;
Can we remove negative margins?

2020-11-27 09:06 UTC, vigilantee commented on frappe/website/css/blog.css
> +}
new line.

2020-11-27 09:08 UTC, vigilantee approved these changes

2020-11-27 09:25 UTC, vigilantee approved these changes, later dismissed

2020-11-30 05:50 UTC, hrwX requested changes

2020-11-30 05:50 UTC, hrwX commented on frappe/website/doctype/blog_post/blog_post.py
> +
```suggestion
```

2020-11-30 05:50 UTC, hrwX commented on frappe/website/doctype/blog_post/blog_post.py
> +		background_image = banner_image
```suggestion
		background_image = website_settings.blog_header
```

2020-11-30 05:50 UTC, hrwX commented on frappe/website/doctype/blog_post/blog_post.py
> +		banner_image = website_settings.blog_header
```suggestion
```

2020-11-30 05:50 UTC, hrwX commented on frappe/website/doctype/blog_post/blog_post.py
> +	banner_image = None
```suggestion
```

2020-12-05 09:54 UTC, hrwX approved these changes, later dismissed

2020-12-09 05:30 UTC, hrwX approved these changes

2020-12-09 05:31 UTC, merged