[WIP] Show due date and task number in Kanban card
DigiThinkIT/frappe pull request #35
Opened 2018-11-27 08:34 UTC by Alchez

First draft design:

![image](https://user-images.githubusercontent.com/13396535/49068649-42af7a00-f24d-11e8-9123-01ee708f10c2.png)

@MattGaiaver, your thoughts?

2018-11-27 13:29 UTC, MattGaiaver commented
I LOVE IT!  Although the client did ask for the actual due date, I like this way better.  Is it possible to present this to them, and then if they still ask for the due date then I'll get back to you?  Otherwise to leave it as is?  So, I'll get an answer for you today?  The CEO is going to be impressed when I'm able to respond back to him in one day's time, thanks for that!  AWESOME!   OR (**new idea**) can the numerical due date go on the same line as the task #? but go in the top right corner of the post it:?  That would be the best of both worlds.

2018-11-27 14:28 UTC, Alchez commented
Having the due date in two places on the same card seems like it might confuse them. We can try putting the due date as hover text on the "Due in..." phrasing.

2018-11-27 14:40 UTC, DeveloperMetal submitted a review, later dismissed

2018-11-27 16:34 UTC, vjFaLk commented
Why even have the document no? Also, let's try to make this upstream as well.

2018-11-27 19:47 UTC, MattGaiaver commented
Preferably the Post It will have the 'Due in' phrasing and the numerical date in the top right corner.

2018-11-28 06:05 UTC, Alchez commented
> Why even have the document no? Also, let's try to make this upstream as well.

Helps in quick lookup for a specific task.

> Preferably the Post It will have the 'Due in' phrasing and the numerical date in the top right corner

Yeah, I'll make that change.

2018-11-28 06:05 UTC, vjFaLk commented
They can just...click on the card to open the task!

2018-11-28 06:07 UTC, MattGaiaver commented
NO not by clicking on it… on the Kanban card!

> On Nov 27, 2018, at 10:05 PM, Valmik <notifications@github.com> wrote:
> 
> They can just...click on the card to open the task!
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/DigiThinkIT/frappe/pull/35#issuecomment-442331008>, or mute the thread <https://github.com/notifications/unsubscribe-auth/An9d-AN6B_nNadgwFcgN_5JlI7HsfEFbks5uzifHgaJpZM4Y0-R5>.
>

2018-11-28 06:09 UTC, vjFaLk commented
@MattGaiaver different discussion lol

2018-11-28 06:10 UTC, Alchez commented
Well, ideally there would be a search bar on the board, but if I ask you to refer to task #8, how are you going to find it on the board without the number? 😛

2018-11-28 06:11 UTC, vjFaLk commented
@Alchez My main issue is that fugly as hell split that won't work if the naming series changes, therefore cannot go upstream

2018-11-28 06:14 UTC, Alchez commented
That's a fair point, but I don't know a quick way to fix that, outside of having document numbers being saved in the doc natively.

2018-11-28 07:01 UTC, Alchez commented
![image](https://user-images.githubusercontent.com/13396535/49134419-77810700-f309-11e8-9d18-81bef884f47e.png)

With the new changes requested by D9.

2018-11-28 09:08 UTC, vjFaLk requested changes
All the files have also changes their modes from 644 to 755. Fix that pls.

2018-11-28 09:08 UTC, vjFaLk commented on frappe/public/css/kanban.css
> +  max-width: 99%;
99%?! What

2018-11-28 09:11 UTC, Alchez commented on frappe/public/css/kanban.css
> +  max-width: 99%;
The CSS gods were displeased with round numbers.

At 100%, it basically hugs the right margin, and looks bad.

2018-11-28 09:24 UTC, Alchez commented
@vjFaLk, fixed the modes.

2018-11-28 09:25 UTC, vjFaLk commented
Merging for now, but make this to upstream. No really. It sucks, but let's try improving it with their help and we'll pull it back.

2018-11-28 09:25 UTC, merged

2018-11-28 09:36 UTC, Alchez commented
PR created upstream: https://github.com/frappe/frappe/pull/6555