Added new end point for AWS get token flow
DigiThinkIT/frappe pull request #352
Opened 2020-12-04 06:45 UTC by vigilantee

Removing the dependency for passing the Client Id for aws cognito flow for getiing the token.

2020-12-04 06:46 UTC, hrwX requested changes

2020-12-04 06:46 UTC, hrwX commented on frappe/integrations/oauth2_logins.py
> +# A method to retrieve the client id from client name and call get_token for Oauth Flow
Add this as docstring

2020-12-04 06:47 UTC, vigilantee commented on frappe/integrations/oauth2_logins.py
> +# A method to retrieve the client id from client name and call get_token for Oauth Flow
ok sure.

2020-12-04 07:04 UTC, vigilantee commented on frappe/integrations/oauth2_logins.py
> +# A method to retrieve the client id from client name and call get_token for Oauth Flow
done.

2020-12-04 07:07 UTC, sahil28297 approved these changes, later dismissed

2020-12-07 10:49 UTC, neilLasrado approved these changes

2020-12-07 14:58 UTC, neilLasrado requested changes

2020-12-07 14:58 UTC, neilLasrado commented on frappe/integrations/oauth2_logins.py
> +    clients = frappe.db.get_list('OAuth Client', filters={'app_name': client_name},fields=['client_id'])
Won't the get_list fail if the user is not logged in? You should use get_all instead

2020-12-09 05:25 UTC, vishdha commented on frappe/integrations/oauth2_logins.py
> +    newForm = frappe.request.form.to_dict()
@vigilantee  frappe.request dont have any form function.
you may try this
frappe.form_dict

2020-12-10 11:00 UTC, vigilantee commented on frappe/integrations/oauth2_logins.py
> +    clients = frappe.db.get_list('OAuth Client', filters={'app_name': client_name},fields=['client_id'])
This api would be called post user authentication by aws.

2020-12-14 10:53 UTC, hrwX commented
@dti-deploy create instance

2020-12-14 11:00 UTC, hrwX commented
@dti-deploy create instance

2020-12-23 12:57 UTC, hrwX requested changes

2020-12-23 12:57 UTC, hrwX commented on frappe/integrations/oauth2_logins.py
> +	frappe.request.form = newForm
```suggestion
	form_dict = frappe.request.form.to_dict()
	form_dict["client_id"] = client_id
	form_dict = ImmutableMultiDict(form_dict)
	frappe.request.form = form_dict
```

2020-12-23 13:00 UTC, hrwX approved these changes

2020-12-23 13:03 UTC, sahil28297 approved these changes

2020-12-23 13:03 UTC, merged