fix: contact number accept number in contact doctype
DigiThinkIT/frappe pull request #448
Opened 2021-01-19 03:48 UTC by nmimsnikhil

[Asana](https://app.asana.com/0/1192407899754728/1199689250118696/f)

![contact_number](https://user-images.githubusercontent.com/56826544/104985555-3b541780-5a37-11eb-8d2a-92d3c5e1b080.gif)

2021-01-19 07:31 UTC, hrwX requested changes

2021-01-19 07:31 UTC, hrwX commented on frappe/contacts/doctype/contact/contact.js
> +	}
This will break for `"-", "(", ")"`

2021-01-19 09:04 UTC, kennethsequeira commented on frappe/contacts/doctype/contact/contact.js
> +	}
Also "+"

2021-01-25 11:06 UTC, sahil28297 commented
Closing this, this should be either fixed for all the fields of numeric type or for none of the fields.

2021-01-25 11:06 UTC, closed without merging