fix: email and phone validations
DigiThinkIT/frappe pull request #458
Opened 2021-01-25 11:13 UTC by hrwX

> Please provide enough information so that others can review your pull request:

> Explain the **details** for making this change. What existing problem does the pull request solve?

> Screenshots/GIFs

2021-02-01 07:44 UTC, sahil28297 commented
@hrwX @DeveloperMetal  This is big change, what should we do about the existing data that's already there is these fields, because if the data is not according to these validations, it will keep on throwing error with no context (the right way to fill these fields) to the users, might break during migration as well and we won't know how to fix it.

2021-02-17 17:32 UTC, DeveloperMetal requested changes
I agree with what @sahil28297 mentioned. If we are doing this we need to make sure we can normalize existing data on existing installations and somehow deal with invalid data already existing on these databases. Otherwise you can easily block an update.

Why not take a less strict path first?

- Warn user of records not complying with normalized rules for say the next couple of months?
- Eventually make that rule a hard requirement. Give our user base time to correct their data and the tools to find bad data

2021-02-17 17:32 UTC, DeveloperMetal commented on frappe/utils/__init__.py
> +	match = re.match(r"([0-9\ \+\_\-\,\.\*\#\(\)]){1,20}$", phone_number)
Not convinced this is the best way to store a normalized phone number. You can still get a wild set of different digits and symbol combinations. That's without event thinking of extension numbers.

 What do you think of only storing digits and spaces(to group numbers)? then, leave the formatting to the frontend?
 It does mean that we should update the frontend controllers to handle phone number formatting(among other things)

2021-02-17 17:32 UTC, DeveloperMetal commented on frappe/utils/__init__.py
> +			Allowed charater are <b>+</b>, <b>-</b>, <b>()</b>, <b>0-9</b>
As mentioned before, the formatting is a bit too loose. And only throwing an exception from the backend will annoy users. We need a frontend update as well to auto format this data as it is being entered. Just good UX to not annoy users.

2021-02-17 17:32 UTC, DeveloperMetal commented on frappe/utils/__init__.py
> +					johndoe@domain.com / johndoe@example.domain.com
Same comments as phone number validation applies here. Needs a frontend update avoid annoying user during input.

2021-02-24 09:45 UTC, closed without merging