fix: adding duplicate entries for rules in role permission
DigiThinkIT/frappe pull request #463
Opened 2021-01-28 05:29 UTC by hitenshKharva

Ref : [Asana Task](https://app.asana.com/0/inbox/1199082161976013)

https://user-images.githubusercontent.com/56474017/106094014-54577980-6157-11eb-8ff4-c9a27066b305.mp4

Earlier [PR ](https://github.com/Bloomstack/frappe/pull/454) reverted due to travis breaking.

2021-01-28 11:35 UTC, sahil28297 commented
@hitenshKharva The return keyword was already there, you have added a msg_print which will just pop a message, the system didn't allow to create duplicate permissions earlier as well. Try to find from where the system generated the existing roles and delete existing duplicate permissions.

2021-02-08 10:52 UTC, hrwX requested changes

2021-02-08 10:52 UTC, hrwX commented on frappe/permissions.py
> +		if not (frappe.flags.in_test and frappe.flags.in_install and frappe.flags.in_migrate):
Combine them

2021-02-09 10:44 UTC, hrwX requested changes

2021-02-09 10:44 UTC, hrwX commented on frappe/core/doctype/custom_docperm/custom_docperm.py
> +		permlevel=self.permlevel, if_owner=0)):
```suggestion
		if frappe.db.get_value('Custom DocPerm', dict(parent=self.doctype, role=self.role, permlevel=self.permlevel, if_owner=0)):
```

2021-02-18 09:22 UTC, hrwX approved these changes

2021-03-22 06:00 UTC, closed without merging