fix: Clear fetch from values on removal of link flied data
DigiThinkIT/frappe pull request #472
Opened 2021-02-05 11:59 UTC by bhattdevarsh

[TASK](https://app.asana.com/0/1192407897953440/1199874277921246/f)

The code Is capable for removing the Fetch From Dependent fields value if the actual Link Values is set to Null.
(It May not Work in case of Custom Logic written for any Particular field. ex: "Sales Order Item Name")
![fetch_from_dependent_fields](https://user-images.githubusercontent.com/58166671/107030711-07b71280-67d7-11eb-9c60-5dc1650f4621.gif)

2021-02-05 12:24 UTC, hrwX requested changes

2021-02-05 12:24 UTC, hrwX commented on frappe/public/js/frappe/form/controls/link.js
> +			me.set_fetch_values(df, docname, value)
```suggestion
			me.set_fetch_values(df, docname, value);
```

2021-02-05 12:24 UTC, hrwX commented on frappe/public/js/frappe/form/controls/link.js
> +			}
```suggestion
		let field_list = this.frm.fetch_dict[df.fieldname] && this.frm.fetch_dict[df.fieldname].fields;
		for (let i in field_list) {
			frappe.model.set_value(df.parent, docname, field_list[i], fetch_values ? fetch_values[i] : fetch_values, df.fieldtype);
		}
```

2021-02-05 12:24 UTC, hrwX commented on frappe/public/js/frappe/form/controls/link.js
>  		}
This doesn't work for Dynamic Fields, you'll have to fix for them too

2021-02-08 09:53 UTC, sahil28297 commented
@bhattdevarsh Any update on this PR?

2021-02-08 11:02 UTC, hrwX approved these changes

2021-02-11 07:52 UTC, sahil28297 approved these changes

2021-02-11 07:52 UTC, merged