fix: fixed send me a copy issue
DigiThinkIT/frappe pull request #474
Opened 2021-02-05 13:55 UTC by meshramsaroj

**Task Link:** https://app.asana.com/0/1192407902292792/1199637017721960/f

**Description:** Added Communication composer settings section for Send me a copy, Send Read Receipt, and Attach Document Print these three fields inside system setting doctype. 
write a code to make field checked or unchecked as per the system setting page

**Screenshot :** 
![image](https://user-images.githubusercontent.com/53329367/107042509-dd218580-67e7-11eb-9c85-0308e95f5724.png)

2021-02-08 08:23 UTC, hrwX requested changes

2021-02-08 08:23 UTC, hrwX commented on frappe/core/doctype/system_settings/system_settings.json
> + "_comments": "[{\"comment\": \"<p><br></p>\", \"by\": \"Administrator\", \"name\": \"8a8e66e79f\"}, {\"comment\": \"<p><br></p>\", \"by\": \"Administrator\", \"name\": \"a92423fcef\"}]",
Remove this

2021-02-08 09:47 UTC, meshramsaroj commented on frappe/core/doctype/system_settings/system_settings.json
> + "_comments": "[{\"comment\": \"<p><br></p>\", \"by\": \"Administrator\", \"name\": \"8a8e66e79f\"}, {\"comment\": \"<p><br></p>\", \"by\": \"Administrator\", \"name\": \"a92423fcef\"}]",
@hrwX removed

2021-02-08 11:01 UTC, hrwX requested changes

2021-02-08 11:01 UTC, hrwX commented on frappe/public/js/frappe/views/communication.js
> +		this.dialog.set_value("send_read_receipt", this.system_settings.send_read_receipt || false);
```suggestion
		this.dialog.set_value("attach_document_print", this.attach_document_print || this.system_settings.attach_document_print || false);
		this.dialog.set_value("send_me_a_copy", this.send_me_a_copy || this.system_settings.send_me_a_copy || false);
		this.dialog.set_value("send_read_receipt", this.send_read_receipt || this.system_settings.send_read_receipt || false);
```

2021-02-09 12:00 UTC, hrwX requested changes

2021-02-09 12:00 UTC, hrwX commented on frappe/public/js/frappe/views/communication.js
> +		this.dialog.set_value("attach_document_print", this.attach_document_print ||this.system_settings.attach_document_print || false);
```suggestion
		this.dialog.set_value("attach_document_print", this.attach_document_print || this.system_settings.attach_document_print || false);
```

2021-02-09 12:00 UTC, hrwX approved these changes

2021-02-10 04:52 UTC, sahil28297 approved these changes

2021-02-10 04:52 UTC, merged