Fix: xlsx export format for financial reports
DigiThinkIT/frappe pull request #507
Opened 2021-03-08 15:27 UTC by rvpasari

2021-03-08 15:29 UTC, rvpasari commented
Depends on: 

https://github.com/Bloomstack/erpnext/pull/1079

2021-03-09 08:46 UTC, hrwX commented on frappe/desk/query_report.py
> +	headers.append(["Period: {0}".format(date_range)])
```suggestion
	headers = [
		["Report: {0}".format(report_name)],
		["Company: {0}".format(filters.get('company', None))],
		["Period: {0} - {1}".format(filters.get("from_date", ""), filters.get("to_date",""))]
	]
```

2021-03-09 08:48 UTC, hrwX requested changes, later dismissed

2021-03-09 08:48 UTC, hrwX commented on frappe/utils/xlsxutils.py
> +				cell.font = Font(bold=True)
```suggestion
			#change header row of table to bold
			if (no_of_values == 1) or (no_of_values > 1 and header_flag):
				cell.font = Font(bold=True)
```

2021-03-10 09:21 UTC, hrwX requested changes

2021-03-10 09:21 UTC, hrwX commented on frappe/desk/query_report.py
> +		]
```suggestion
	]
```

2021-03-10 09:21 UTC, hrwX approved these changes

2021-03-10 09:33 UTC, sahil28297 approved these changes

2021-03-10 09:33 UTC, merged