fix: fixed title of contact doctype and added new field for title
DigiThinkIT/frappe pull request #514
Opened 2021-03-18 07:52 UTC by meshramsaroj

**Task Link:** https://app.asana.com/0/1199639423748061/1199955181219855/f

**Description:** Added title field into contact doctype. Fix contact's title behavior, now the title will update as per changes. also made name value equal to CONTACT00001

**Screenshot:** 

- Before
![image](https://user-images.githubusercontent.com/53329367/111583839-00762200-87e3-11eb-9c68-cc8e38f32400.png)

- After
![contact_title_name](https://user-images.githubusercontent.com/53329367/111590852-a9754a80-87ec-11eb-89f2-08c4c7ee4cb5.gif)

2021-03-18 09:55 UTC, hrwX approved these changes, later dismissed

2021-03-18 09:55 UTC, hrwX commented on frappe/contacts/doctype/contact/contact.json
> + "autoname": "CONTACT.#####",
- autoname should look like `Contact-0001`

2021-03-18 09:55 UTC, hrwX commented on frappe/contacts/doctype/contact/contact.py
> +		self.title = f'{self.first_name} {self.last_name or ""}'
```suggestion
		self.title = "{0} {1}".format(self.first_name, self.last_name)
```

2021-03-18 09:55 UTC, hrwX commented on frappe/contacts/doctype/contact/contact.py
> +		if frappe.db.exists("Contact", self.title):
- self.title is not the actual name!
```suggestion
		if frappe.db.exists("Contact", {"title": self.title}):
```

2021-03-18 09:55 UTC, hrwX commented on frappe/contacts/doctype/contact/contact.py
> +		# 	[cstr(self.get(f)).strip() for f in ["first_name", "last_name"]]))
Remove the commented code

2021-03-18 10:21 UTC, meshramsaroj commented on frappe/contacts/doctype/contact/contact.py
> +		# 	[cstr(self.get(f)).strip() for f in ["first_name", "last_name"]]))
removed commented code

2021-03-18 10:22 UTC, meshramsaroj commented on frappe/contacts/doctype/contact/contact.py
> +		if frappe.db.exists("Contact", self.title):
fixed this change

2021-03-18 10:23 UTC, meshramsaroj commented on frappe/contacts/doctype/contact/contact.json
> + "autoname": "CONTACT.#####",
made name format like Contact-0001
![image](https://user-images.githubusercontent.com/53329367/111611041-06c7c680-8802-11eb-8dab-a5e59a605dde.png)

2021-03-18 10:23 UTC, meshramsaroj commented on frappe/contacts/doctype/contact/contact.py
> +		self.title = f'{self.first_name} {self.last_name or ""}'
fixed this change

2021-03-19 05:26 UTC, hrwX requested changes

2021-03-19 05:26 UTC, hrwX commented on frappe/contacts/doctype/contact/contact.py
> +		self.name= make_autoname("Contact-.####")
```suggestion
		self.name = make_autoname("Contact-.####")
```

2021-03-19 05:26 UTC, hrwX commented on frappe/contacts/doctype/contact/contact.py
> +		if frappe.db.exists("Contact", {"title":self.title}):
```suggestion
		if frappe.db.exists("Contact", {"title": self.title}):
```

2021-03-19 05:38 UTC, sahil28297 requested changes

2021-03-19 05:38 UTC, sahil28297 commented on frappe/contacts/doctype/contact/contact.py
> +from frappe.model.naming   import make_autoname
```suggestion
from frappe.model.naming import make_autoname
```

2021-03-19 05:39 UTC, sahil28297 approved these changes, later dismissed

2021-03-19 07:08 UTC, hrwX requested changes

2021-03-19 07:08 UTC, hrwX commented on frappe/contacts/doctype/contact/contact.json
> + "modified": "2021-03-18 15:44:20.711966",
Enable `show_title_field_in_link` for Contact

2021-03-19 07:19 UTC, meshramsaroj commented on frappe/contacts/doctype/contact/contact.json
> + "modified": "2021-03-18 15:44:20.711966",
Enabled show_title_field_in_link field

2021-03-19 07:26 UTC, hrwX approved these changes, later dismissed

2021-03-19 07:28 UTC, hrwX commented
@meshramsaroj write a patch to update the new title fields

2021-03-22 05:15 UTC, hrwX requested changes

2021-03-22 05:15 UTC, hrwX commented on frappe/patches/v12_0/set_contact_title.py
> +            """% (contact))
```suggestion
	frappe.reload_doc("contacts", "doctype", "contact")
	frappe.db.sql("""
		UPDATE `tabContact`
		SET title=name
	""")
```

2021-03-22 05:36 UTC, hrwX requested changes

2021-03-22 05:36 UTC, hrwX commented on frappe/contacts/doctype/contact/contact.py
>  	def autoname(self):
Remove this autoname and put this in doctype, refer [this](https://frappeframework.com/docs/user/en/basics/doctypes/naming)

2021-03-22 05:36 UTC, hrwX commented on frappe/contacts/doctype/contact/contact.py
> +	def before_save(self):
- Put this in validate

2021-03-22 05:54 UTC, hrwX requested changes

2021-03-22 05:54 UTC, hrwX commented on frappe/contacts/doctype/contact/contact.py
>  			self.name = append_number_if_name_exists('Contact', self.name)
Remove this autoname function completely

2021-03-22 05:54 UTC, hrwX commented on frappe/contacts/doctype/contact/contact.py
> +	def before_save(self):
```suggestion
	def set_title(self):
```

2021-03-22 05:54 UTC, hrwX commented on frappe/contacts/doctype/contact/contact.py
> +		self.before_save()
```suggestion
		self.set_title()
```

2021-03-22 06:23 UTC, hrwX approved these changes

2021-03-22 06:32 UTC, neilLasrado approved these changes

2021-03-22 11:22 UTC, sahil28297 approved these changes

2021-03-22 11:22 UTC, merged