feat: Mobile App Roles in User Roles
DigiThinkIT/frappe pull request #520
Opened 2021-03-31 09:23 UTC by sahil28297

- add "For Mobile Application" in Role
- adds a section in Roles for "Mobile Application Roles"

![image](https://user-images.githubusercontent.com/37302950/113122002-d6841d00-9230-11eb-970d-d398527db2fc.png)

2021-03-31 16:40 UTC, DeveloperMetal approved these changes, later dismissed

2021-04-05 06:43 UTC, hrwX requested changes

2021-04-05 06:43 UTC, hrwX commented on frappe/core/doctype/user/user.py
> +	order_by="name")
```suggestion
	}, fields = ["name", "for_mobile_application"], order_by="name")
```

2021-04-05 06:43 UTC, hrwX commented on frappe/core/doctype/user/user.py
> +		"mobile_app_roles": [role.get("name") for role in roles if role.get("for_mobile_application")]
- Iterate over the roles list once and segregate it

2021-04-05 09:24 UTC, hrwX approved these changes

2021-04-05 09:25 UTC, merged