feat: CKEditor 5
DigiThinkIT/frappe pull request #526
Opened 2021-04-15 15:09 UTC by hrwX

> Please provide enough information so that others can review your pull request:

> Explain the **details** for making this change. What existing problem does the pull request solve?

> Screenshots/GIFs

2021-04-15 15:11 UTC, hrwX commented
@dti-deploy create instance

2021-04-15 15:23 UTC, sahil28297 commented
@dti-deploy create instance

2021-04-15 15:23 UTC, sahil28297 commented
@dti-deploy create instance

2021-04-15 15:24 UTC, sahil28297 commented
@dti-deploy create instance

2021-04-15 15:25 UTC, sahil28297 commented
@dti-deploy create instance

2021-04-15 15:27 UTC, dti-deploy commented
An error occurred while executing the following command:
					```git checkout bs-apr-sprint-2```
You may manually fix the issue using: `ssh 139.59.26.123 -l frappe`
					Traceback:
``````

2021-05-05 02:34 UTC, DeveloperMetal requested changes
Looking pretty good. Just a couple of super minor nitpicks.

2021-05-05 02:34 UTC, DeveloperMetal commented on frappe/public/js/frappe/form/controls/ckeditor-plugins/Base64UploadAdapter.js
> +export default class Adapter {
Rename the class to something like Base64Adapter please. Just to keep class name a bit more unique.

2021-05-05 02:34 UTC, DeveloperMetal commented on frappe/public/css/email.css
> +  background-color: #80bd9e;
Why this color change on the email css?

2021-05-05 09:43 UTC, hrwX commented on frappe/public/css/email.css
> +  background-color: #80bd9e;
I guess the build process updated the primary button color, since I changed the primary color to bloomstack green in variables.less

2021-05-05 12:49 UTC, DeveloperMetal commented on frappe/public/css/email.css
> +  background-color: #80bd9e;
@hrwX Not that it matters too much, but lets keep the color consistent with core until we have gone through our UI updates

2021-05-06 12:20 UTC, DeveloperMetal submitted a review, later dismissed

2021-05-12 08:17 UTC, sahil28297 approved these changes

2021-05-12 08:19 UTC, merged