Fix: creation of new customer primary contact and its linking to cont…
DigiThinkIT/frappe pull request #530
Opened 2021-04-22 06:13 UTC by shruti2323

…act doctype

> Please provide enough information so that others can review your pull request:

> Explain the **details** for making this change. What existing problem does the pull request solve?

> Screenshots/GIFs

2021-04-22 06:15 UTC, shruti2323 commented
![Customersnap09](https://user-images.githubusercontent.com/80836439/115664989-408b7000-a360-11eb-9ebf-62fd39b12748.PNG)
![Customersnap08](https://user-images.githubusercontent.com/80836439/115664996-41bc9d00-a360-11eb-92e4-869e4e2299a1.PNG)

https://user-images.githubusercontent.com/80836439/115664997-42553380-a360-11eb-9405-de3e97b42a05.mp4

![Customersnap07](https://user-images.githubusercontent.com/80836439/115665005-45502400-a360-11eb-9439-f53653bd3990.PNG)
![Customersnap06](https://user-images.githubusercontent.com/80836439/115665008-45e8ba80-a360-11eb-8041-e299fe03a458.PNG)
![Customersnap05](https://user-images.githubusercontent.com/80836439/115665009-45e8ba80-a360-11eb-8009-2553161dfcfd.PNG)

https://user-images.githubusercontent.com/80836439/115665010-46815100-a360-11eb-8e67-0e796a6e4623.mp4

![Customersnap03](https://user-images.githubusercontent.com/80836439/115665015-47b27e00-a360-11eb-830e-3ba48def73d4.PNG)
![Customersnap02](https://user-images.githubusercontent.com/80836439/115665017-47b27e00-a360-11eb-9224-e78fa10a7469.PNG)
![Customersnap01](https://user-images.githubusercontent.com/80836439/115665018-484b1480-a360-11eb-99f4-7d48360c334e.PNG)

https://user-images.githubusercontent.com/80836439/115665022-48e3ab00-a360-11eb-8593-9580720d2921.mp4

2021-04-22 06:20 UTC, shruti2323 commented
Fix: 
1. On creation of new Contact without entering last name, field was fetching as "None" for last_name.
2. was unable to add new customer primary contact.
3. On creation of customer primary contact, should fetch only first_name if first name is present and 
should be able to fetch first_name , last_name , not "None" -> if first_name and last_name is present and should be linked to Contact Doctype.

2021-04-22 06:53 UTC, vishdha requested changes

2021-04-22 06:53 UTC, vishdha commented on frappe/desk/search.py
> +				# "label": r[1],
@shruti2323  Remove this commented code

2021-04-22 07:25 UTC, shruti2323 commented on frappe/desk/search.py
> +				# "label": r[1],
ok

2021-04-22 13:24 UTC, hrwX requested changes

2021-04-22 13:24 UTC, hrwX commented on frappe/contacts/doctype/contact/contact.py
> +
- You are introducing old code back in the framework

2021-04-22 13:24 UTC, hrwX commented on frappe/contacts/doctype/contact/contact.py
> +			self.title = "{0} {1}".format(self.first_name, self.last_name)
- Correct fix has to be in ERPNext and not in framework

2021-04-26 05:47 UTC, vishdha commented on frappe/contacts/doctype/contact/contact.py
> +
```suggestion
	def autoname(self):
		# concat first and last name
		self.name = " ".join(filter(None,
			[cstr(self.get(f)).strip() for f in ["first_name", "last_name"]]))

		if frappe.db.exists("Contact", self.name):
			self.name = append_number_if_name_exists('Contact', self.name)

		# concat party name if reqd
		for link in self.links:
			self.name = self.name + '-' + link.link_name.strip()
			break

```

2021-04-26 05:47 UTC, vishdha commented on frappe/contacts/doctype/contact/contact.py
> +			self.title = "{0} {1}".format(self.first_name, self.last_name)
@hrwX  I think this is right. it has to be resolve in the framework because we are adding autoname for contact which is part of the framework only.

2021-04-26 05:51 UTC, vishdha commented on frappe/contacts/doctype/contact/contact.py
> +
Reference from v13

2021-04-26 05:53 UTC, vishdha commented on frappe/contacts/doctype/contact/contact.py
> +			self.title = "{0} {1}".format(self.first_name, self.last_name)
@hrwX  what do you think?

2021-04-27 06:02 UTC, hrwX requested changes

2021-04-27 06:02 UTC, hrwX commented on frappe/contacts/doctype/contact/contact.py
> +			self.title = "{0} {1}".format(self.first_name, self.last_name)
@vishdha, we have to filter the contacts. Saroj has already changed the autoname for contacts

2021-04-30 08:12 UTC, hrwX commented
@shruti2323 Any updates ?

2021-04-30 09:37 UTC, hrwX commented
@shruti2323 Closing this PR in favour of https://github.com/Bloomstack/erpnext/pull/1212

2021-04-30 09:37 UTC, closed without merging