feat: url field validations added
DigiThinkIT/frappe pull request #542
Opened 2021-05-03 13:16 UTC by nehasacher143

Task: https://app.asana.com/0/1188592895233593/1199686835850180/f

Steps: Add 'URL' (case-sensitive) in options of the field you want to apply these validations

GIF:
![Peek 2021-05-03 18-45](https://user-images.githubusercontent.com/45919049/116880608-d6b47580-ac3f-11eb-8c98-d0537d13379a.gif)

2021-05-04 06:56 UTC, hrwX requested changes

2021-05-04 06:56 UTC, hrwX commented on frappe/public/js/frappe/utils/utils.js
> +			case "URL":
- Why are we changing this to uppercase, this will break something else. Also in the data field for URL, we are using a different function to validate the url.
- Lets not change the regex here directly

2021-05-04 06:56 UTC, hrwX commented
@dti-deploy create instance

2021-05-04 07:21 UTC, hrwX requested changes

2021-05-04 07:21 UTC, hrwX commented on frappe/public/js/frappe/form/controls/data.js
> +		}
- Do not add any if condition for check if URL.
- Revert the code, after the input is setup, check if it is an url field, only then append `fa external-link-alt` after the input field

2021-05-06 10:39 UTC, hrwX requested changes

2021-05-06 10:39 UTC, hrwX commented on frappe/model/base_document.py
> +			if data_field_options == "url":
```suggestion
			if data_field_options == "URL":
```

2021-05-06 10:39 UTC, hrwX commented on frappe/public/js/frappe/form/controls/data.js
> +		.prependTo(this.input_area);
```suggestion
			.attr("type", this.input_type)
			.attr("autocomplete", "off")
			.addClass("input-with-feedback form-control")
			.prependTo(this.input_area);
```

2021-05-06 10:39 UTC, hrwX commented on frappe/public/js/frappe/form/controls/data.js
> +		if (this.df.options === "Url") {
```suggestion
		if (this.df.options === "URL") {
```

2021-05-06 10:39 UTC, hrwX commented on frappe/public/js/frappe/form/controls/data.js
> +						this.doc.parenttype
```suggestion
							'name', (val) => {
								if (val) {
									this.set_description(__('{0} already exists. Select another name', [val.name]));
								}
							},
							this.doc.parenttype
```

2021-05-06 10:39 UTC, hrwX commented on frappe/public/js/frappe/form/controls/data.js
> +		.attr("placeholder", this.df.placeholder || "");
```suggestion
			.attr("data-fieldtype", this.df.fieldtype)
			.attr("data-fieldname", this.df.fieldname)
			.attr("placeholder", this.df.placeholder || "");
```

2021-05-06 10:39 UTC, hrwX commented on frappe/public/js/frappe/form/controls/data.js
> +
Check if df.options === "URL" only then add a listener

2021-05-07 06:10 UTC, hrwX requested changes

2021-05-07 06:10 UTC, hrwX commented on frappe/public/js/frappe/form/controls/data.js
> +		if(me.df.options === 'URL')
```suggestion
		if(me.df.options != 'URL') return;

```

2021-05-07 06:10 UTC, hrwX commented on frappe/public/js/frappe/form/controls/data.js
> +			me.$input_wrapper.find(".btn-open") && me.$input_wrapper.find(".btn-open").toggleClass("hide");
```suggestion
			me.$input_wrapper && me.$input_wrapper.find(".btn-open") &&
			me.$input_wrapper.find(".btn-open").hasClass("hide") && me.$input_wrapper.find(".btn-open").removeClass("hide");
```

2021-05-07 06:10 UTC, hrwX commented on frappe/utils/__init__.py
> +			URL should be in the format of https://site.test
- Use frappe.throw
```suggestion
			frappe.msgprint(frappe._("""
			{0} is not a valid URL.
			<br><br>
			URL should be of the format <b>example.com</b>, <b>www.example.com</b>, <b>https://example.com</b>
```

2021-05-07 06:10 UTC, hrwX commented on frappe/public/js/frappe/form/controls/data.js
> +		}
```suggestion
		} else {
			me.$input_wrapper && me.$input_wrapper.find(".btn-open") &&
			!me.$input_wrapper.find(".btn-open").hasClass("hide") && me.$input_wrapper.find(".btn-open").addClass("hide");
		}
```

2021-05-07 06:10 UTC, hrwX commented on frappe/public/js/frappe/form/controls/data.js
> +	},
```suggestion
	}
```

2021-05-07 10:34 UTC, hrwX requested changes

2021-05-07 10:34 UTC, hrwX commented on frappe/utils/__init__.py
> +		""").format(frappe.bold(url)))
Duplicate Code

2021-05-07 10:36 UTC, hrwX approved these changes

2021-05-07 10:37 UTC, sahil28297 approved these changes

2021-05-07 10:37 UTC, merged