feat: max precision in database
DigiThinkIT/frappe pull request #544
Opened 2021-05-05 07:39 UTC by hrwX

- This PR, decouples precision in the system ie the field precision in the database will be high but the precision shown in the UI will be user configurable.
- ![image](https://user-images.githubusercontent.com/7310479/117109861-eef0d580-ada2-11eb-8acd-0c0461efff4c.png)
- Why this PR ?
    - If the field precision is set low, we end up losing data in the round off.

2021-05-18 06:22 UTC, sahil28297 requested changes

2021-05-18 06:22 UTC, sahil28297 commented on frappe/core/doctype/docfield/docfield.json
> +   "description": "Set non-standard precision for a Float or Currency field in the database.",
Can we set the default here as 9 here as well so that one does not have to look into the js file for finding the default value?

2021-05-18 06:22 UTC, sahil28297 commented on frappe/core/doctype/docfield/docfield.json
> +   "depends_on": "eval:in_list([\"Float\", \"Currency\", \"Percent\"], doc.fieldtype)",
Same default value here as well?

2021-05-18 06:22 UTC, sahil28297 commented on frappe/custom/doctype/custom_field/custom_field.json
> +   "description": "Set non-standard precision for a Float or Currency field in the database.",
same default value?

2021-05-18 06:22 UTC, sahil28297 commented on frappe/custom/doctype/custom_field/custom_field.json
> +   "depends_on": "eval:in_list([\"Float\", \"Currency\", \"Percent\"], doc.fieldtype)",
same default value?

2021-05-18 06:22 UTC, sahil28297 commented on frappe/custom/doctype/customize_form_field/customize_form_field.json
> +   "description": "Set non-standard precision for a Float or Currency field in the database.",
same default value?

2021-05-18 06:22 UTC, sahil28297 commented on frappe/custom/doctype/customize_form_field/customize_form_field.json
> +   "depends_on": "eval:in_list([\"Float\", \"Currency\", \"Percent\"], doc.fieldtype)",
same default value?

2021-05-18 06:22 UTC, sahil28297 commented on frappe/custom/doctype/customize_form/customize_form.js
> +		frappe.model.set_value(cdt, cdn, "display_precision", precision_field ? "2" : "");
instead of 9 and 2, can we not fetch it from system settings?

2021-05-18 06:22 UTC, sahil28297 commented on frappe/public/js/frappe/form/formatters.js
> +		let precision = cint(docfield.display_precision) || cint(docfield.precision) || 2;
instead of `2` can we fetch it from system settings?

2021-05-18 06:22 UTC, sahil28297 commented on frappe/public/js/frappe/form/formatters.js
> +			|| 2;
same

2021-05-18 07:46 UTC, hrwX commented on frappe/core/doctype/docfield/docfield.json
> +   "description": "Set non-standard precision for a Float or Currency field in the database.",
We cant, because it will set the default precision value for all the docfields irrespective of field type, and it messes up the json

2021-05-18 07:46 UTC, hrwX commented on frappe/core/doctype/docfield/docfield.json
> +   "depends_on": "eval:in_list([\"Float\", \"Currency\", \"Percent\"], doc.fieldtype)",
We cant, because it will set the default precision value for all the docfields irrespective of field type, and it messes up the json

2021-05-18 07:46 UTC, hrwX commented on frappe/custom/doctype/custom_field/custom_field.json
> +   "description": "Set non-standard precision for a Float or Currency field in the database.",
We cant, because it will set the default precision value for all the docfields irrespective of field type, and it messes up the json

2021-05-18 07:46 UTC, hrwX commented on frappe/custom/doctype/custom_field/custom_field.json
> +   "depends_on": "eval:in_list([\"Float\", \"Currency\", \"Percent\"], doc.fieldtype)",
We cant, because it will set the default precision value for all the docfields irrespective of field type, and it messes up the json

2021-05-18 07:46 UTC, hrwX commented on frappe/custom/doctype/customize_form_field/customize_form_field.json
> +   "description": "Set non-standard precision for a Float or Currency field in the database.",
We cant, because it will set the default precision value for all the docfields irrespective of field type, and it messes up the json

2021-05-18 07:46 UTC, hrwX commented on frappe/custom/doctype/customize_form_field/customize_form_field.json
> +   "depends_on": "eval:in_list([\"Float\", \"Currency\", \"Percent\"], doc.fieldtype)",
We cant, because it will set the default precision value for all the docfields irrespective of field type, and it messes up the json

2021-05-19 07:03 UTC, sahil28297 approved these changes, later dismissed

2021-05-19 08:30 UTC, neilLasrado submitted a review, later dismissed

2021-05-19 08:30 UTC, neilLasrado commented
This needs heavy testing, let's deploy this PR and test.

2021-06-07 04:30 UTC, neilLasrado approved these changes, later dismissed

2021-06-07 06:18 UTC, sahil28297 approved these changes

2021-06-07 06:49 UTC, merged