feat: pdf file autoname added
DigiThinkIT/frappe pull request #561
Opened 2021-05-12 11:04 UTC by vishdha

TASK ID: [ASANA](https://app.asana.com/0/1192407894480744/1200251298276147)

2021-05-13 05:05 UTC, hrwX requested changes

2021-05-13 05:05 UTC, hrwX commented on frappe/utils/print_format.py
> +		name = set_name_from_naming_options(file_auto_name, doc)
```suggestion
	if file_auto_name and not doc:
		# based on type of format used set_name_form_naming_option return result.
		doc = frappe.get_doc(doctype, name)
		name = set_name_from_naming_options(file_auto_name, doc)
```

2021-05-13 05:05 UTC, hrwX commented on frappe/core/doctype/doctype/doctype.json
> +  "file_auto_name",
- Why was this field not added to customize form ?

2021-05-13 05:54 UTC, vishdha commented on frappe/utils/print_format.py
> +		name = set_name_from_naming_options(file_auto_name, doc)
```suggestion
	if file_auto_name and not doc: 
```
this will fail if Request for a quotation as function call from RFQ send doc args

2021-05-13 05:55 UTC, vishdha commented on frappe/utils/print_format.py
> +		name = set_name_from_naming_options(file_auto_name, doc)
I mean it will bypass this condition in rfq

2021-05-17 08:45 UTC, hrwX requested changes

2021-05-17 08:45 UTC, hrwX commented on frappe/custom/doctype/customize_form/customize_form.json
> +  "file_auto_name",
```suggestion
  "file_auto_name",
```

Can we rename this to file_autoname for the sake of consistency

2021-05-18 05:24 UTC, hrwX commented on frappe/custom/doctype/customize_form/customize_form.json
> +   "label": "Auto Name Section"
```suggestion
   "label": "Naming"
```

2021-05-18 05:25 UTC, hrwX approved these changes

2021-05-18 06:32 UTC, sahil28297 approved these changes

2021-05-18 06:33 UTC, merged