Chore: Fix of of create material request at frappe end
DigiThinkIT/frappe pull request #566
Opened 2021-05-18 04:57 UTC by shruti2323

As per the discussion while PR review, added this fix at frappe level not specific to material req. for production plan.
Asana task : https://app.asana.com/0/1200073273462988/1200035083056715
Below is the attached gif : -

https://user-images.githubusercontent.com/80836439/118592406-83a3fc00-b7c3-11eb-81e2-65b9eb0fc0fa.mp4

2021-05-18 05:20 UTC, hrwX requested changes

2021-05-18 05:20 UTC, hrwX commented on frappe/public/js/frappe/ui/messages.js
> +			}
```suggestion
			if (ifyes) ifyes();
			d.hide();
```

- Can you follow the coding style of frappe so that the code looks better.
- If everyone adds their own coding style to the code base, itll be a mess.

2021-05-18 05:20 UTC, hrwX commented on frappe/public/js/frappe/ui/messages.js
>  		secondary_action_label: __("No")
```suggestion
		secondary_action_label: __("No"),
		secondary_action: function() {
			if (ifno) ifno();
			d.hide();
		}
```

2021-05-18 09:26 UTC, shruti2323 commented on frappe/public/js/frappe/ui/messages.js
>  		secondary_action_label: __("No")
ok

2021-05-19 06:58 UTC, hrwX approved these changes

2021-05-19 07:28 UTC, sahil28297 commented
@shruti2323 Test

2021-05-19 07:29 UTC, sahil28297 commented
Test

2021-05-19 11:47 UTC, sahil28297 approved these changes

2021-05-19 11:49 UTC, merged