chore: add the validation msg to Party
DigiThinkIT/frappe pull request #573
Opened 2021-05-19 12:25 UTC by harshmule-git

<img width="1624" alt="Screenshot 2021-05-19 at 5 54 33 PM" src="https://user-images.githubusercontent.com/77478531/118812124-69554580-b8cb-11eb-84e8-646259d4c703.png">

2021-05-20 06:03 UTC, sahil28297 requested changes

2021-05-20 06:03 UTC, sahil28297 commented on frappe/public/js/frappe/form/controls/dynamic_link.js
> +					var msg = `Please Select ${this.df.options}`
You are currently displaying the fieldname, find a way to display the label of the field.

2021-05-20 06:19 UTC, harshmule-git commented on frappe/public/js/frappe/form/controls/dynamic_link.js
> +					var msg = `Please Select ${this.df.options}`
okay!

2021-05-20 12:40 UTC, harshmule-git commented on frappe/public/js/frappe/form/controls/dynamic_link.js
> +					var msg = `Please Select ${this.df.options}`
<img width="1680" alt="Screenshot 2021-05-20 at 6 09 49 PM" src="https://user-images.githubusercontent.com/77478531/118979901-94589b80-b996-11eb-80c2-76b9286de32f.png">

2021-05-21 04:58 UTC, vishdha requested changes

2021-05-21 04:58 UTC, vishdha commented on frappe/public/js/frappe/form/controls/dynamic_link.js
> +					var msg = `Please select '${input[0]['placeholder']}' before selecting ${this.input.placeholder}`
```suggestion
					let msg = `Please select '${input[0]['placeholder']}' before selecting ${this.input.placeholder}`
```

2021-05-21 05:07 UTC, vishdha requested changes

2021-05-21 05:07 UTC, vishdha commented on frappe/public/js/frappe/form/controls/dynamic_link.js
> +					var msg = `Please select '${input[0]['placeholder']}' before selecting ${this.input.placeholder}`
```suggestion
					frappe.msgprint(__(`Please select '${input[0]['placeholder']}' before selecting ${this.input.placeholder}`))
```

2021-05-21 05:07 UTC, vishdha requested changes

2021-05-21 05:07 UTC, vishdha commented on frappe/public/js/frappe/form/controls/dynamic_link.js
> +					frappe.msgprint(msg)
```suggestion
```

2021-05-24 06:06 UTC, hrwX requested changes

2021-05-24 06:06 UTC, hrwX commented on frappe/public/js/frappe/form/controls/dynamic_link.js
> +					frappe.msgprint(__(`Please select '${input[0]['placeholder']}' before selecting ${this.input.placeholder}`));
- Not the placeholder, you have to show the docfield's label

2021-05-24 06:36 UTC, harshmule-git commented on frappe/public/js/frappe/form/controls/dynamic_link.js
> +					frappe.msgprint(__(`Please select '${input[0]['placeholder']}' before selecting ${this.input.placeholder}`));
not getting a label in the response which are coming!

2021-05-25 06:47 UTC, hrwX commented on frappe/public/js/frappe/form/controls/dynamic_link.js
> +					frappe.msgprint(__(`Please select '${label}' before selecting ${this.df.label}`));
```suggestion
					frappe.msgprint(__(`Please select <b>${label}</b> before selecting <b>${this.df.label}</b>`));
```

2021-05-25 06:49 UTC, hrwX submitted a review, later dismissed

2021-05-31 04:36 UTC, sahil28297 approved these changes

2021-05-31 04:40 UTC, hrwX approved these changes, later dismissed

2021-05-31 04:43 UTC, sahil28297 requested changes

2021-05-31 04:43 UTC, sahil28297 commented on frappe/public/js/frappe/form/controls/dynamic_link.js
> +					let label = frappe.meta.get_label(this.df.doctype, this.df.options)
```suggestion
				if (!input.val()) {
					let label = frappe.meta.get_label(this.df.doctype, this.df.options);
```

2021-05-31 04:46 UTC, sahil28297 approved these changes

2021-05-31 04:46 UTC, merged