feat: popup description
DigiThinkIT/frappe pull request #579
Opened 2021-05-24 04:47 UTC by hrwX

- New way to show description for fields
- ![image](https://user-images.githubusercontent.com/7310479/119297770-40d99c80-bc79-11eb-9ccf-ba5f8e7786f9.png)

2021-05-28 08:16 UTC, rvpasari requested changes

2021-05-28 08:16 UTC, rvpasari commented on frappe/public/js/frappe/form/controls/datetime.js
> +	refresh_input: function() {
Is this just for the help icon? Or did you accidentally include changes for timezone in this PR as well?

2021-05-31 06:19 UTC, neilLasrado commented on frappe/public/js/frappe/form/controls/datetime.js
> +	refresh_input: function() {
Looks correct to me. For date/time fields the timezone is being pushed into the description. @hrwX can you please confirm that?

2021-06-02 06:40 UTC, hrwX commented on frappe/public/js/frappe/form/controls/datetime.js
> +	refresh_input: function() {
Yes, we show the timezone as help description for date/time/datetime fields

2021-06-02 13:07 UTC, neilLasrado approved these changes

2021-06-02 13:07 UTC, merged