feat: edit social post
DigiThinkIT/frappe pull request #586
Opened 2021-05-26 13:28 UTC by shantanu-kadam-epi

Asana link: https://app.asana.com/0/1200358785304462/1200345362093948

![image](https://user-images.githubusercontent.com/60215482/119667575-0a0bae00-be54-11eb-9e31-89e472743e2f.png)

![image](https://user-images.githubusercontent.com/60215482/119667802-3d4e3d00-be54-11eb-9419-1051f95fc0b9.png)

2021-05-27 07:26 UTC, hrwX requested changes

2021-05-27 07:26 UTC, hrwX commented on frappe/social/doctype/post/post.py
> +	return post_edit
```suggestion
	return frappe.get_doc('Post', post_name)
```

2021-05-27 07:26 UTC, hrwX commented on frappe/social/doctype/post/post.py
> +
```suggestion
```

2021-05-27 07:26 UTC, hrwX commented on frappe/public/js/frappe/social/components/Post.vue
> +			<div class="text-muted comment-label">{{ __('Update a post') }}</div>
```suggestion
			<div class="text-muted comment-label">{{ __('Update') }}</div>
```

2021-05-27 07:26 UTC, hrwX commented on frappe/public/js/frappe/social/components/Post.vue
> +		{
```suggestion
		update_post() {
```

2021-05-27 07:26 UTC, hrwX commented on frappe/public/js/frappe/social/components/Post.vue
> +		make_edit_section(edit_post_data){
```suggestion
		make_edit_section(edit_post_data) {
```

2021-05-28 05:11 UTC, hrwX requested changes

2021-05-28 05:11 UTC, hrwX commented on frappe/public/js/frappe/social/components/Post.vue
> +				}).then((res) => this.make_edit_section(res))
```suggestion
			frappe.xcall('frappe.social.doctype.post.post.edit_post', {
				'post_name': this.post.name
			}).then((res) => this.make_edit_section(res))
```

2021-05-31 04:31 UTC, sahil28297 approved these changes

2021-05-31 04:39 UTC, hrwX approved these changes

2021-05-31 04:47 UTC, merged