feat: status master and status workflow added
DigiThinkIT/frappe pull request #601
Opened 2021-06-02 09:07 UTC by vishdha

2021-06-02 13:07 UTC, hrwX requested changes

2021-06-02 13:07 UTC, hrwX commented on frappe/core/doctype/status_workflow/status_workflow.json
> +   "ignore_xss_filter": 1,
```suggestion
```

2021-06-02 13:07 UTC, hrwX commented on frappe/core/doctype/status_workflow/status_workflow.py
> +		self.name = self.document_type+ "-" + self.status
- Put this in auto_name in doctype itself

2021-06-02 13:07 UTC, hrwX commented on frappe/core/doctype/status_workflow/status_workflow.py
> +	# 			frappe.throw(_("The Condition '{0}' is invalid").format(self.condition))
```suggestion
```

2021-06-02 13:07 UTC, hrwX commented on frappe/core/doctype/status/status.py
> +class Status(Document):
- Are we not moving the status fields of existing doctypes to Status doctype ?

2021-06-04 10:02 UTC, vishdha commented on frappe/core/doctype/status/status.py
> +class Status(Document):
we replacing select field to link

2021-06-04 10:03 UTC, vishdha commented on frappe/core/doctype/status_workflow/status_workflow.py
> +		self.name = self.document_type+ "-" + self.status
let be it should be coded here. the front end will give the control to the user for change in formating. there is no issue right now but let be coded here

2021-06-07 04:15 UTC, hrwX commented on frappe/core/doctype/status_workflow/status_workflow.py
> +		self.name = self.document_type+ "-" + self.status
This does not make sense to hardcode something in code that can be achieved with configuration

2021-06-07 04:16 UTC, hrwX requested changes

2021-06-07 04:16 UTC, hrwX commented on frappe/core/doctype/status/status.py
> +class Status(Document):
I cannot see the json for doctypes in the framework for which we changed select field to link

2021-06-15 06:01 UTC, sahil28297 commented
@vishdha what's up with this PR?

2021-06-15 12:01 UTC, vishdha commented on frappe/core/doctype/status/status.py
> +class Status(Document):
its in erpnext

2021-06-28 12:18 UTC, closed without merging