feat: added geocode api key in google settings and changed api key field type to password
DigiThinkIT/frappe pull request #607
Opened 2021-06-04 11:46 UTC by MyuddinKhatri

2021-06-07 04:14 UTC, hrwX requested changes

2021-06-07 04:14 UTC, hrwX commented on frappe/integrations/doctype/google_settings/test_google_settings.py
> +	pass
Delete this file

2021-06-09 06:01 UTC, hrwX approved these changes

2021-06-11 06:07 UTC, sahil28297 approved these changes

2021-06-11 06:08 UTC, merged

2021-06-11 06:09 UTC, sahil28297 commented
@MyuddinKhatri can you open a PR on bs-jun-sprint-1 branch?