feat: Mandatory depends on logic added
DigiThinkIT/frappe pull request #619
Opened 2021-06-10 08:11 UTC by vishdha

2021-06-11 06:32 UTC, hrwX submitted a review, later dismissed

2021-06-11 07:09 UTC, sahil28297 commented
@vishdha fix Sider issues

2021-06-14 05:08 UTC, sahil28297 requested changes

2021-06-14 05:08 UTC, sahil28297 commented on frappe/core/doctype/doctype/test_doctype.py
> +			 or_filters={
```suggestion
			or_filters={
```

2021-06-14 10:33 UTC, vishdha commented
> @vishdha fix Sider issues

Resolved

2021-06-15 05:58 UTC, sahil28297 approved these changes

2021-06-15 05:59 UTC, merged