Fix change the phone validation
DigiThinkIT/frappe pull request #622
Opened 2021-06-11 13:46 UTC by nehasacher143

Task/Fix: Fix the format phone method to provide the correct value

2021-06-14 04:22 UTC, hrwX requested changes

2021-06-14 04:22 UTC, hrwX commented on frappe/public/js/frappe/utils/utils.js
> +		return formatted.isValid() ? formatted.formatInternational() : false;
- Did you check this in `data.js ` ??

2021-06-16 05:44 UTC, hrwX approved these changes, later dismissed

2021-06-16 07:22 UTC, sahil28297 submitted a review, later dismissed

2021-06-16 11:30 UTC, hrwX submitted a review, later dismissed

2021-06-16 11:43 UTC, sahil28297 approved these changes

2021-06-16 11:44 UTC, merged