fix: allow support for custom db host and port
DigiThinkIT/frappe pull request #630
Opened 2021-06-17 13:48 UTC by sahil28297

2021-06-17 13:56 UTC, hrwX requested changes

2021-06-17 13:56 UTC, hrwX commented on frappe/commands/site.py
> +		force=True, db_type=frappe.conf.db_type)
- db_port, db_host ?

2021-06-17 14:02 UTC, sahil28297 commented on frappe/commands/site.py
> +		force=True, db_type=frappe.conf.db_type)
not required

2021-06-18 04:33 UTC, hrwX approved these changes

2021-06-18 05:07 UTC, merged