feat: added pagination and filter for addresses and contacts
DigiThinkIT/frappe pull request #641
Opened 2021-06-24 14:48 UTC by MyuddinKhatri

2021-06-24 15:09 UTC, MyuddinKhatri commented
@hrwX , @DeveloperMetal , @nehasacher143 I need to move the search Contact and Search address field above the listing, can you guys suggest me something?

2021-06-26 06:50 UTC, hrwX requested changes

2021-06-26 06:50 UTC, hrwX commented on frappe/public/js/frappe/utils/address_and_contact.js
> +	paginate_address: function (frm) {
- Commonify paginate_contact and paginate_address

2021-06-28 14:43 UTC, DeveloperMetal requested changes
Move the search box above the addresses component. You can prepend a container update to do your work.

And as noted scope all your selectors, fetching general classes kills page performance and will add odd bugs on other parts of the page which are hidden and later displayed.

2021-06-28 14:43 UTC, DeveloperMetal commented on frappe/public/js/frappe/utils/address_and_contact.js
> +		$('div[title="contact_html"]').append("<div class='contact_pagination'><p>Hello</p></div>");
Do you realize that this selector: `$('div[title="contact_html"]')`
Will match any div with title "contact_html" even if the dom is hidden or behind the current page?

It means that you are potentially touching dom outside of the current page you expect this to work on. Please scope your selectors to the current container.

Not sure about the frappe.contacts instance but most classes have either a $page or $container you can use to scope things and not bleed behavior onto other similar selectors.

2021-06-28 14:43 UTC, DeveloperMetal commented on frappe/public/js/frappe/utils/address_and_contact.js
> +		$('body').on('click',`.page_number`,function(){
Same issue here on container scope and performance. Don't attach live event onto the body. It means that jquery will scan the entire dom every time an element is added for that **.page_number** class.

Scope it to the page or even the field container, must faster to iterate.

2021-06-30 05:57 UTC, sahil28297 commented
@MyuddinKhatri What's up with this PR? Also fix Sider issues

2021-06-30 06:05 UTC, MyuddinKhatri commented
> @MyuddinKhatri What's up with this PR? Also fix Sider issues

need to change some css here

2021-06-30 09:45 UTC, MyuddinKhatri commented
@hrwX and @sahil28297 changes are done please have a look.

2021-07-02 07:12 UTC, hrwX requested changes

2021-07-02 07:12 UTC, hrwX commented on frappe/public/js/frappe/utils/address_and_contact.js
> +		frm.fields_dict['contact_html1'] && $(frm.fields_dict['contact_html1'].wrapper).html("");
- `address_html1` is not available in frm.

2021-07-02 07:12 UTC, hrwX commented on frappe/public/js/frappe/utils/address_and_contact.js
> +		let per_page = 3;
```suggestion
		let per_page = 5;
```

2021-07-07 04:36 UTC, hrwX submitted a review, later dismissed

2021-07-07 04:41 UTC, hrwX commented
@MyuddinKhatri Fix sider issues.

2021-07-07 23:51 UTC, DeveloperMetal requested changes
I still see jquery selector scoping issues that can hurt browser performance. The .on(<event>, <class>, <callback>) method will trigger every time an element is added to the dom specially from the document scope. You can limit that traversal by scoping to the current page.

2021-07-07 23:51 UTC, DeveloperMetal commented on frappe/public/js/frappe/utils/address_and_contact.js
> +		$(document).on('click', '.contact-box a.delete_contact', function () {
Scope this please, you are forcing jquery to traverse the entire dom to set this event

2021-07-07 23:51 UTC, DeveloperMetal commented on frappe/public/js/frappe/utils/address_and_contact.js
> +		$(document).on('click', '.contact-box a.unlink_contact', function () {
Scope this please, you are forcing jquery to traverse the entire dom to set this event

2021-07-07 23:51 UTC, DeveloperMetal commented on frappe/public/js/frappe/utils/address_and_contact.js
> +		$(document).on('click', '.btn-contact-link', function () {
Scope this please, you are forcing jquery to traverse the entire dom to set this event

2021-07-07 23:51 UTC, DeveloperMetal commented on frappe/public/js/frappe/utils/address_and_contact.js
> +		$(document).on('click', '.address-box a.delete_address', function () {
Scope this please, you are forcing jquery to traverse the entire dom to set this event

2021-07-07 23:51 UTC, DeveloperMetal commented on frappe/public/js/frappe/utils/address_and_contact.js
> +		$(document).on('click', '.address-box a.unlink_address', function () {
Scope this please, you are forcing jquery to traverse the entire dom to set this event

2021-07-07 23:51 UTC, DeveloperMetal commented on frappe/public/js/frappe/utils/address_and_contact.js
> +		$(document).on('click', '.btn-address-link', function () {
Scope this please, you are forcing jquery to traverse the entire dom to set this event

2021-07-07 23:51 UTC, DeveloperMetal commented on frappe/public/js/frappe/utils/address_and_contact.js
> +		$(`body`).on('click', `.${pagination_class} .page_number`, function () {
Scope this please, you are forcing jquery to traverse the entire dom to set this event

2021-07-09 13:08 UTC, nehasacher143 submitted a review, later dismissed
@MyuddinKhatri  Looks good to me

@DeveloperMetal @hrwX Please review

2021-07-12 09:34 UTC, hrwX requested changes

2021-07-12 09:34 UTC, hrwX commented on frappe/contacts/address_and_contact.py
> +	doc = json.loads(doc)
```suggestion
	doc = frappe.parse_json(doc)
```

2021-07-12 09:34 UTC, hrwX commented on frappe/contacts/address_and_contact.py
> +	doc = json.loads(doc)
```suggestion
	doc = frappe.parse_json(doc)
```

2021-07-12 09:35 UTC, hrwX approved these changes, later dismissed

2021-07-13 12:55 UTC, DeveloperMetal approved these changes, later dismissed

2021-07-13 13:25 UTC, sahil28297 requested changes

2021-07-13 13:25 UTC, sahil28297 commented on frappe/contacts/address_and_contact.py
> +import json
```suggestion
```

2021-07-13 13:28 UTC, sahil28297 approved these changes

2021-07-13 13:29 UTC, merged