Fix help button issue
DigiThinkIT/frappe pull request #643
Opened 2021-06-25 13:23 UTC by meshramsaroj

**Task Link:** https://app.asana.com/0/1194051119161697/1200464637755574/f

**Screenshot:** 

- Before
![image](https://user-images.githubusercontent.com/53329367/123431018-71995280-d5e6-11eb-97be-c3ac57dadc5a.png)

- After
![image](https://user-images.githubusercontent.com/53329367/123431159-98578900-d5e6-11eb-9e62-3c21a7268d5b.png)

2021-06-26 06:53 UTC, hrwX requested changes

2021-06-26 06:53 UTC, hrwX commented on frappe/core/doctype/user/user_list.js
> +
- This is the wrong fix.
- Remove the relevant code from `list_sidebar.html`

2021-06-28 05:27 UTC, meshramsaroj commented on frappe/core/doctype/user/user_list.js
> +
Fixed this change

2021-06-28 06:33 UTC, hrwX approved these changes

2021-06-28 08:37 UTC, sahil28297 approved these changes

2021-06-28 08:38 UTC, merged