fix: attach file/image to unsaved document
DigiThinkIT/frappe pull request #691
Opened 2021-07-19 12:12 UTC by hrwX

- [Asana](https://app.asana.com/0/1192118403864545/1199908440007463)
- When attaching files/images to `Attach/Attach Image`, framework tries to upload the file to server. While doing so, the file gets attached to a temperory document for eg: doctype=Job Applicant and name=New Job Applicant 1.
- Due to this the file remains an orphan.
- In this PR, the system will link the file to a document once the document is inserted in the system

2021-07-20 15:46 UTC, DeveloperMetal approved these changes, later dismissed

2021-07-23 05:11 UTC, sahil28297 approved these changes

2021-07-23 05:12 UTC, sahil28297 requested changes

2021-07-23 05:12 UTC, sahil28297 commented on frappe/public/js/frappe/form/controls/attach.js
> +			this.frm.doc.__unsaved_attachments = []
```suggestion
			this.frm.doc.__unsaved_attachments = [];
```

2021-07-23 05:12 UTC, sahil28297 commented on frappe/public/js/frappe/form/controls/attach.js
> +			this.frm.doc.__unsaved_attachments = []
```suggestion
			this.frm.doc.__unsaved_attachments = [];
```

2021-07-23 05:13 UTC, sahil28297 approved these changes

2021-07-23 06:27 UTC, merged