feat: added warning message when user type changed
DigiThinkIT/frappe pull request #692
Opened 2021-07-20 12:08 UTC by meshramsaroj

**Task Link:** https://app.asana.com/0/1194051119161697/1200367023041052/f

**Description:** Added warning message when user type is changed from website user to system user and vise versa.

**Screenshot:**

-  when user type changed from website user to system user
![image](https://user-images.githubusercontent.com/53329367/126321133-557aa354-69f9-4165-aee7-3a55c15034cb.png)

- when user type changed from system user to website user
![image](https://user-images.githubusercontent.com/53329367/126321176-6ac141eb-c713-499b-a5b3-448355c611c8.png)

2021-07-20 12:11 UTC, hrwX requested changes

2021-07-20 12:11 UTC, hrwX commented on frappe/core/doctype/user/user.py
> -	def find_by_credentials(cls, user_name, password, validate_password=True):
Why did we remove this ?

2021-07-20 12:36 UTC, meshramsaroj commented on frappe/core/doctype/user/user.py
> -	def find_by_credentials(cls, user_name, password, validate_password=True):
this code has been removed while checking out to the new branch.
now I restore removed code

2021-07-22 08:44 UTC, hrwX approved these changes, later dismissed

2021-07-22 11:28 UTC, sahil28297 requested changes

2021-07-22 11:28 UTC, sahil28297 commented on frappe/core/doctype/user/user.py
> +				msgprint(_("User Type changed from {0} to {1}").format(old_user_type, self.user_type), title=_('Warning'), indicator='red')
```suggestion
```

2021-07-22 11:28 UTC, sahil28297 commented on frappe/core/doctype/user/user.py
> +				msgprint(_("User Type changed from {0} to {1}").format(old_user_type, self.user_type), title=_('Warning'), indicator='red')
```suggestion

		if self.user_type != old_user_type:
			msgprint(_("User Type changed from {0} to {1}").format(old_user_type, self.user_type), title=_('Warning'), indicator='red')
```

2021-07-23 06:03 UTC, meshramsaroj commented on frappe/core/doctype/user/user.py
> +				msgprint(_("User Type changed from {0} to {1}").format(old_user_type, self.user_type), title=_('Warning'), indicator='red')
resolved

2021-07-23 06:26 UTC, sahil28297 approved these changes

2021-07-23 06:27 UTC, merged