[Fix] Make production order in sales order
DigiThinkIT/frappe pull request #7
Opened 2017-12-20 10:19 UTC by sushantnadkar

![image](https://user-images.githubusercontent.com/8912289/34202271-4e1597ac-e59d-11e7-8d4e-d271f1351716.png)

2017-12-22 18:50 UTC, DeveloperMetal requested changes
Can you update the jquery selectors to use the dialog api?

you can target the currently open dialog with:

`cur_dialog.$wrapper.find(...)`

etc...

2017-12-28 18:03 UTC, forellana-digithinkit commented on frappe/public/js/frappe/form/grid.js
> +				for(i = 0; i < $(rows).find(".row-index.sortable-handle.col.col-xs-1").find("span").length; i++) {
yeah, change this to:

for(var i=0; ... etc ...

Or you'll have a leaking variable to the global scope

2017-12-28 18:04 UTC, forellana-digithinkit commented on frappe/public/js/frappe/form/grid.js
> +			if (dialog_title == "Select Items to Manufacture") {
Same as previous issue, add:

var dialog_title = ... etc ...

Or you'll have this var leak to the global scope

2018-01-04 15:28 UTC, DeveloperMetal approved these changes

2018-01-05 07:01 UTC, merged