fix: fixed working of New Contact and New Address
DigiThinkIT/frappe pull request #706
Opened 2021-08-02 06:58 UTC by MyuddinKhatri

2021-08-02 09:19 UTC, hrwX approved these changes, later dismissed

2021-08-03 05:36 UTC, sahil28297 approved these changes

2021-08-03 05:38 UTC, sahil28297 requested changes

2021-08-03 05:38 UTC, sahil28297 commented on frappe/public/js/frappe/utils/address_and_contact.js
> +		if(frm.layout_for_address.fields_dict['address_html1'] && $(frm.fields_dict['address_html1'].wrapper)) {
```suggestion
		if (frm.layout_for_address.fields_dict['address_html1'] && $(frm.fields_dict['address_html1'].wrapper)) {
```

2021-08-03 05:38 UTC, sahil28297 commented on frappe/public/js/frappe/utils/address_and_contact.js
> +		if(frm.layout_for_address.fields_dict['contact_html1'] && $(frm.fields_dict['contact_html1'].wrapper)) {
```suggestion
		if (frm.layout_for_address.fields_dict['contact_html1'] && $(frm.fields_dict['contact_html1'].wrapper)) {
```

2021-08-03 05:38 UTC, sahil28297 commented on frappe/public/js/frappe/utils/address_and_contact.js
> +			.html(frappe.render_template("address_list", frm.doc.__onload))
```suggestion
				.html(frappe.render_template("address_list", frm.doc.__onload))
```

2021-08-03 05:38 UTC, sahil28297 commented on frappe/public/js/frappe/utils/address_and_contact.js
> +			.html(frappe.render_template("contact_list", frm.doc.__onload))
```suggestion
				.html(frappe.render_template("contact_list", frm.doc.__onload))
```

2021-08-03 06:14 UTC, hrwX approved these changes

2021-08-03 06:39 UTC, merged