Improvements to Dashboard
DigiThinkIT/frappe pull request #736
Opened 2021-08-25 13:49 UTC by neilLasrado

2021-08-25 16:05 UTC, sahil28297 requested changes
Also have a look at the sider issues

2021-08-25 16:05 UTC, sahil28297 commented on frappe/public/js/frappe/widgets/chart_widget.js
> +				if ( e.target && e.target.dataset.pointIndex != undefined) {
```suggestion
				if (e.target && e.target.dataset && e.target.dataset.pointIndex) {
```

2021-08-30 05:50 UTC, sahil28297 commented
@neilLasrado This file `frappe/public/js/frappe/views/dashboard/dashboard_view.js`was intended to be used for this feature https://discuss.erpnext.com/t/new-feature-configurable-dashboard-view/61114. I think we didn't import the part to put it in the views section of sidebar. If we do not wont it, lets merge the PR, otherwise, lets keep all of the files and see if we can get this working.

2021-08-30 11:10 UTC, neilLasrado commented
@sahil28297 good find, Let's get this merged for now. We can later import the 'Dashboard; view code if needed.

I strongly feel the code must be commodified into a single file even if we introduce this feature

2021-08-31 16:56 UTC, sahil28297 approved these changes

2021-08-31 16:57 UTC, merged