refactor: merge vue component from core to frappe
DigiThinkIT/frappe pull request #752
Opened 2021-09-13 09:00 UTC by vishdha

2021-09-16 08:36 UTC, sahil28297 requested changes
@vishdha the code looks good, but in your GIF, the text inside the card looks center aligned, it should be left aligned.

2021-09-20 12:47 UTC, vishdha commented
> @vishdha the code looks good, but in your GIF, the text inside the card looks center aligned, it should be left aligned.

Yeah it depends on CSS Change

2021-09-21 05:42 UTC, sahil28297 commented
> > @vishdha the code looks good, but in your GIF, the text inside the card looks center aligned, it should be left aligned.
> 
> Yeah it depends on CSS Change

Can we get the CSS moved here then? I have commented the same on your erpnext PR for CSS change.

2021-09-22 04:59 UTC, sahil28297 approved these changes

2021-09-22 05:00 UTC, merged