feat: new progress bar component added to dashboard
DigiThinkIT/frappe pull request #756
Opened 2021-09-20 05:45 UTC by nehasacher143

**Task:** https://bloomstack.com/desk#Form/Task/TASK-2021-00243

**Screenshot:**
![screenshot-localhost_8005-2021 09 20-11_14_15](https://user-images.githubusercontent.com/45919049/133961096-eb48ed2b-176c-4d89-b1af-3e65866a9f34.png)

2021-09-22 13:18 UTC, hrwX requested changes

2021-09-22 13:18 UTC, hrwX commented on frappe/public/js/frappe/form/dashboard.js
> +		var progress_chart = this.make_progress_chart(title);
```suggestion
		let progress_chart = this.make_progress_chart(title);
```

2021-09-22 13:18 UTC, hrwX commented on frappe/public/js/frappe/form/dashboard.js
> +		if(!$.isArray(percent)) {
```suggestion
		if (!$.isArray(percent)) {
```

2021-09-22 13:18 UTC, hrwX commented on frappe/public/js/frappe/form/dashboard.js
> +		var progress = $('<ul class="progress_chart"></ul>').appendTo(progress_chart);
```suggestion
		let progress = $('<ul class="progress_chart"></ul>').appendTo(progress_chart);
```

2021-10-04 13:49 UTC, nehasacher143 commented
@sahil28297 @MyuddinKhatri @neilLasrado @DeveloperMetal  Please review this one

2021-10-07 09:42 UTC, neilLasrado approved these changes

2021-10-19 16:24 UTC, DeveloperMetal approved these changes

2021-11-01 17:26 UTC, closed without merging