Feature/jest
DigiThinkIT/frappe pull request #767
Opened 2021-09-28 07:17 UTC by diptigandhi24

I have added jest using npm. To make it work with the npm test command I added the script jest to the package.json.
Note: you cannot run a test from the root directory, you need to inside the directory which has a node modules folder.
Run: npm test bloom.test.js 
its a dummy test to see if it works

2021-09-28 10:00 UTC, DeveloperMetal requested changes
Just noting what we talked over the changes on chat for record keeping.

Things to change:

- add jest.config.js and set it up to pickup *.specs.js
- modify the npm script to point to the /frappe/public/js/bloomstack folder by default

2021-09-28 12:24 UTC, DeveloperMetal requested changes

2021-09-28 12:24 UTC, DeveloperMetal commented on package.json
> +    "test":"jest"
change this to:

```
"test": "jest ./frappe/public/js/bloomstack"
```

So for now we'll only test the new codebase

2021-09-28 12:27 UTC, diptigandhi24 commented on package.json
> +    "test":"jest"
I added it to jest.config.js and its working fine from there also, but I will add it  package.json

2021-09-28 14:39 UTC, DeveloperMetal requested changes
Small typo to correct.

Do run the command to make sure it works as expected

2021-09-28 14:39 UTC, DeveloperMetal commented on package.json
> +    "test":"jest .frappe/public/js/bloomstack/"
This is missing a slash between . and frappe:

```
./frappe/public/js/bloomstack/
```

2021-10-04 05:40 UTC, Anurag810 commented
@diptigandhi24 and @DeveloperMetal please follow the guideline while creating the Pull Request request.
@DeveloperMetal Please ensure that before reviewing the Pull Request.

https://github.com/Bloomstack/erpnext/wiki/Guidelines-for-writing-better-pull-request-description-for-features
https://github.com/Bloomstack/erpnext/wiki/Guidelines-for-writing-better-pull-request-description-for-fixes

2021-10-04 10:43 UTC, DeveloperMetal requested changes

2021-10-04 10:43 UTC, DeveloperMetal commented on frappe/public/js/bloomstack/controllers/page/index.js
> +		console.log("Calling make dom")
remove console  log

2021-10-04 10:43 UTC, DeveloperMetal commented on frappe/public/js/bloomstack/react/hooks/use_html.jsx
> +let complex_props_count = 0;
In the original code these two would get reset on every call to to_html.
Moving them out here prevents that and keeps upping that count.

So if you want to extract the function you could pull the counters into the function and pass the entire objects instead. So that you are not relying on the external variables.

Try not updating variables outside your functions unless you have a scoped context otherwise your code is not isolated.

```js
export function segregateComplexSimpleProps(props) {
  let simple_props_count = 0;
  let complex_props_count = 0;
  return Object.entries(props).reduce((p, c) => { ... }
}, [{}, {}]);
```

2021-10-04 10:43 UTC, DeveloperMetal commented on frappe/public/js/bloomstack/react/hooks/use_html.spec.js
> +        const [simple_props, complex_props] = Object.entries(obj).reduce(segregateComplexSimpleProps, [{}, {}]);
so, if you do the changes mentioned on the extracted function you would be testing different things here.

Your test becomes simpler too. You should know your simple and complex counts from the get go. Just check the length of the returned variables.

2021-10-05 10:47 UTC, DeveloperMetal requested changes

2021-10-05 10:47 UTC, DeveloperMetal commented on frappe/public/js/bloomstack/react/hooks/use_html.jsx
> +},[{},{}]);}
Please fix formatting

2021-10-05 10:47 UTC, DeveloperMetal commented on frappe/public/js/bloomstack/controllers/page/index.js
> +		console.log("Calling make dom")
console. log still here

2021-10-05 10:47 UTC, DeveloperMetal commented on frappe/public/js/bloomstack/react/hooks/use_html.spec.js
> +    test("Counting simle and complex props after segregating",()=>{
typo simle -> simple

2021-10-05 10:47 UTC, DeveloperMetal commented on frappe/public/js/bloomstack/react/hooks/use_html.spec.js
> +    })
You testing the same thing 4 times. There is no need for that as you are not changing anything between the data sets.

Instead do different tests on having different combinations of simple/complex counts and keys returned.

ex pseudo code(not tested just written here for example):

```js
// test combinations broken into simple and complex
const simple = {simple1: 1, simple2: "simple"};
const complex = { complex1: {}, complex2: [] };

// test simple and complex
const test1 = { ...simple, ...complex };
// test complex only
const test2 = { ...complex }
// test simple only
const test3 = { ...simple };

const [t1_simple, t1_complex] = segregateComplexSimpleProps(test1);
const [t2_simple, t2_complex] = segregateComplexSimpleProps(test2);
const [t3_simple, t3_complex] = segregateComplexSimpleProps(test3);

expect(t1_simple).toMatchObject(simple);
expect(t1_complex).toMatchObject(complex);

expect(t2_simple).toMatchObject({});
expect(t2_complex).toMatchObject(complex);

expect(t3_simple).toMatchObject(simple);
expect(t3_complex).toMatchObject({});

```

2021-10-05 10:47 UTC, DeveloperMetal commented on package.json
> +    "socket.io": "^2.4.1",
Don't update other libraries without going through testing and should probably be done in a different PR anyways.

2021-10-19 14:49 UTC, closed without merging