fix: fixed tooltip for dashboard charts with currency formatter
DigiThinkIT/frappe pull request #768
Opened 2021-09-29 18:13 UTC by MyuddinKhatri

2021-09-29 18:15 UTC, DeveloperMetal submitted a review, later dismissed

2021-09-29 18:19 UTC, nehasacher143 approved these changes, later dismissed

2021-09-29 18:21 UTC, neilLasrado approved these changes

2021-09-29 19:14 UTC, neilLasrado requested changes
Will not work for non currency tool tips

2021-09-30 08:39 UTC, neilLasrado submitted a review, later dismissed

2021-09-30 11:26 UTC, neilLasrado approved these changes

2021-09-30 11:40 UTC, sahil28297 approved these changes

2021-09-30 11:40 UTC, merged