feat: added download attachment feature for to doctype's action menu
DigiThinkIT/frappe pull request #780
Opened 2021-10-18 18:23 UTC by meshramsaroj

**Task Link:** https://bloomstack.com/desk#Form/Task/TASK-2021-00394

**Description:** Added download option into action menu of the file list and also added download attachment feature to all doctype's action menu

**GIF:** 

- Feature for File doctype

![docwnolad-files](https://user-images.githubusercontent.com/53329367/137785131-3cf8f6fe-8c26-492d-9b2a-d47894cb3ab4.gif)

- Feature for all doctypes

![feat-for-all-doctypes](https://user-images.githubusercontent.com/53329367/137785800-9e198662-1c46-445e-a664-7223e5212ebd.gif)

2021-10-18 18:26 UTC, ghost commented
✅ Sider has resolved the errors or warnings via the commit 36d80a0! See the [analysis result](https://sider.review/gh/repos/66088811/pulls/780) for details.

---

You can [turn off such notifications](https://sider.review/gh/repos/66088811/settings#notifications) if unnecessary.

2021-10-19 16:23 UTC, neilLasrado requested changes

2021-10-19 16:23 UTC, neilLasrado commented on frappe/core/doctype/file/file.py
> +def download_bulk_files(filters):
rename this function to bulk_download_files

2021-10-19 16:23 UTC, neilLasrado commented on frappe/core/doctype/file/file.py
> +	output_path = frappe.get_site_path('private', 'files', output_filename)
what if the file attached is public? check if this will work

2021-10-20 05:37 UTC, sahil28297 requested changes

2021-10-20 05:37 UTC, sahil28297 commented on frappe/public/js/frappe/list/list_view.js
> +		};
Both are same functions, combine them and pass label, api_method_path as an argument to the function below in if statements:
```
if doctype=File
    bulkdownload(label=something, api_method_path=/api/something)
 else
    bulddownload(label=something_else, api_method_path=/api/something_else)
```

2021-10-20 05:37 UTC, sahil28297 commented on frappe/core/doctype/file/file.py
> +	output_path = frappe.get_site_path('private', 'files', output_filename)
this is for the new downloaded file I guess, i.e where the file will be downloaded, so all of the downloaded file of the used will be stored as a private file

2021-10-20 05:37 UTC, sahil28297 commented on frappe/core/doctype/file/file.py
> +	frappe.local.response.type = "download"
This same function is present on line 942, why did you make a new function for this?

2021-10-20 15:35 UTC, meshramsaroj commented on frappe/core/doctype/file/file.py
> +	frappe.local.response.type = "download"
I have created this method so that I can get a bunch of files in one .zip file for File doctype.
Now, I have removed this method from the existing file and written condition in the existing function i.e.download_zip_files.

2021-10-20 15:36 UTC, meshramsaroj commented on frappe/public/js/frappe/list/list_view.js
> +		};
Used same method for both labels by passing label value as parameter

2021-10-21 06:17 UTC, sahil28297 approved these changes

2021-10-21 06:18 UTC, merged