Chore: Exapnd Section Breaks to better search doctype
DigiThinkIT/frappe pull request #82
Opened 2019-05-07 13:52 UTC by DeeMysterio

Please read the [Pull Request Checklist](https://github.com/frappe/erpnext/wiki/Pull-Request-Checklist) to ensure you have everything that is needed to get your contribution merged.

2019-05-13 09:41 UTC, Er-Naren719 approved these changes
Code looks good.

2019-05-14 07:15 UTC, vjFaLk commented
@DeeMysterio Please also make this to Frappe Upstream. Take @Alchez's help.

2019-05-14 09:02 UTC, Alchez requested changes

2019-05-14 09:02 UTC, Alchez commented on frappe/public/js/frappe/form/toolbar.js
> +					var collapsible_fields = all_fields_in_doc.filter(returnCollapsibleFields);
Get rid of the function, do it inline.

```suggestion
					let collapsible_fields = all_fields_in_doc.filter((field) => field.fieldtype == "Section Break");
```

2019-05-14 09:21 UTC, Alchez requested changes

2019-05-14 09:21 UTC, Alchez commented on frappe/public/js/frappe/form/toolbar.js
>  			if(is_submittable && docstatus == 1) {
Allow expanding the sections even for Draft (and maybe unsaved) documents.

2019-05-20 10:58 UTC, merged