Expand sections
DigiThinkIT/frappe pull request #93
Opened 2019-05-29 12:12 UTC by DeeMysterio

2019-05-29 12:20 UTC, Alchez requested changes

2019-05-29 12:20 UTC, Alchez commented on frappe/public/js/frappe/form/toolbar.js
> +				let section_fields = me.frm.meta.fields.filter((field) => field.fieldtype == "Section Break");
Remove this line. You've already declared it on line 184.

2019-05-29 12:20 UTC, Alchez commented on frappe/public/js/frappe/form/toolbar.js
> -				this.page.add_menu_item(__("Request Feedback"), function() {
I think you accidentally deleted this button.

2019-05-31 08:48 UTC, Alchez approved these changes

2019-05-31 08:48 UTC, merged

2019-12-11 09:23 UTC, Alchez commented
@DeeMysterio, can you make this upstream?

2019-12-12 08:21 UTC, DeeMysterio commented
> @DeeMysterio, can you make this upstream?

Did this [here](https://github.com/frappe/frappe/pull/9025)