feat(core): add icons for expanding and collapsing Section Breaks
DigiThinkIT/frappe pull request #97
Opened 2019-06-04 14:04 UTC by DeeMysterio

![expand-collapse-icons](https://user-images.githubusercontent.com/13060550/58885312-98cf0f80-86ff-11e9-9f1d-94c2932b202b.gif)

2019-06-04 14:24 UTC, Alchez requested changes

2019-06-04 14:24 UTC, Alchez commented on frappe/public/js/frappe/form/toolbar.js
>  			this.page.add_menu_item(__("Expand Sections"), function () {
If we're doing icons now, do we still need the menu items?

2019-06-04 14:24 UTC, Alchez commented on frappe/public/js/frappe/form/toolbar.js
> +			this.print_icon = this.page.add_action_icon("fa fa-angle-double-down fa-lg", function() {
You don't need to store it in a variable.

2019-06-04 14:24 UTC, Alchez commented on frappe/public/js/frappe/form/toolbar.js
> +		let me = this;
This is not needed, since your scope is not changing in the loop. Simply use `this`.

2019-06-04 14:31 UTC, DeeMysterio commented on frappe/public/js/frappe/form/toolbar.js
>  			this.page.add_menu_item(__("Expand Sections"), function () {
@neilLasrado says Yes. This is the same case as that of Print.

2019-06-06 11:17 UTC, vjFaLk requested changes

2019-06-06 11:17 UTC, vjFaLk commented on frappe/public/js/frappe/form/toolbar.js
> +			this.frm.get_field(section.fieldname).collapse(collapse);
`collapse` is a bad name. I think it should be `collapse_state` or just `state`

2019-06-07 10:24 UTC, vjFaLk approved these changes

2019-06-07 10:25 UTC, vjFaLk approved these changes

2019-06-07 10:25 UTC, merged

2019-08-12 12:30 UTC, dti-deploy commented
:tada: This PR is included in version 1.2.0 :tada:

The release is available on [GitHub release](https://github.com/DigiThinkIT/frappe/releases/tag/v1.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2019-12-12 08:13 UTC, DeeMysterio commented
Made this to [develop](https://github.com/frappe/frappe/pull/9025)